<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>üçò üë©üèø‚Äçü§ù‚Äçüë©üèæ üò¨ Controlador de errores est√°ndar en RxJava2 o por qu√© RxJava provoca bloqueos de la aplicaci√≥n incluso si se implementa onError üì≠ üëÉ üöµüèø</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="El art√≠culo discutir√° RxJava2 en RxJava2 versi√≥n 2.0.6 y posterior. Si alguien choc√≥ y no puede resolverlo, o no escuch√≥ sobre este problema en absolu...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Controlador de errores est√°ndar en RxJava2 o por qu√© RxJava provoca bloqueos de la aplicaci√≥n incluso si se implementa onError</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/post/422611/"> El art√≠culo discutir√° <code>RxJava2</code> en <code>RxJava2</code> versi√≥n <code>2.0.6</code> y posterior.  Si alguien choc√≥ y no puede resolverlo, o no escuch√≥ sobre este problema en absoluto, le pido un gato.  Impulsaron la traducci√≥n de problemas en la <code>production</code> despu√©s de la transici√≥n de <code>RxJava1</code> a <code>RxJava2</code> .  El original fue escrito el 28 de diciembre de 2017, pero es mejor averiguarlo tarde que nunca. <br><div style="text-align:center;"><img src="https://habrastorage.org/webt/sh/49/yi/sh49yi0mhl6-tmfir_fdvlkmcny.png"></div><a name="habracut"></a>  Todos somos buenos desarrolladores y <code>onError</code> errores en <code>onError</code> cuando usamos <code>RxJava</code> .  Esto significa que nos hemos protegido de los bloqueos de aplicaciones, ¬øverdad? <br><br>  <i>No, no es verdad</i> <br><br>  A continuaci√≥n, veremos un par de ejemplos en los que la aplicaci√≥n se <code>RxJava</code> debido a <code>RxJava</code> , incluso si <code>onError</code> implementa correctamente. <br><br><h3>  <code>RxJava</code> errores b√°sicos en <code>RxJava</code> </h3><br>  <code>RxJava</code> usa <code>RxJavaPlugins.onError</code> como el controlador de errores base.  Maneja todos los errores que no se pueden entregar al suscriptor.  Por defecto, todos los errores se env√≠an, por lo que pueden producirse bloqueos cr√≠ticos de la aplicaci√≥n. <br>  <a href=""><code>    2.0.6</code></a> describen este comportamiento: <br><blockquote>  Uno de los objetivos del dise√±o 2.x es la falta de errores perdidos.  A veces, una secuencia termina o se cancela antes de que la fuente <code>onError</code> .  En este caso, el error no tiene a d√≥nde ir y se env√≠a a <code>RxJavaPlugins.onError</code> <br></blockquote><br>  Si RxJava no tiene un controlador de errores b√°sico, dichos errores se ocultar√°n a nosotros y los desarrolladores no estar√°n al tanto de posibles problemas en el c√≥digo. <br><br>  A partir de la versi√≥n <code>2.0.6</code> , <code>RxJavaPlugins.onError</code> intenta ser m√°s inteligente y comparte errores de biblioteca / implementaci√≥n y situaciones en las que no se puede entregar un error.  Los errores asignados a la categor√≠a de "errores" se llaman como est√°n, mientras que el resto se envuelven en <code>UndeliverableException</code> y luego se llaman.  Puede ver toda esta l√≥gica <a href="">aqu√≠</a> ( <code>isBug</code> <code>onError</code> e <code>isBug</code> ). <br><br>  Uno de los principales errores de los novatos en el <code>RxJava</code> <code>OnErrorNotImplementedException</code> es <code>OnErrorNotImplementedException</code> .  Este error ocurre si <code>observable</code> causa un error y el m√©todo <code>onError</code> no est√° implementado en el suscriptor.  Este error es un ejemplo de un error que para el controlador de errores b√°sico <code>RxJava</code> es un "error" y no se convierte en una <code>UndeliverableException</code> no <code>UndeliverableException</code> . <br><br><h3>  Excepci√≥n imposible de entregar </h3><br>  Dado que los errores relacionados con los "errores" son f√°ciles de corregir, no nos detendremos en ellos.  Los errores que <code>RxJava</code> envuelve en una <code>RxJava</code> son m√°s interesantes, ya que no siempre es obvio por qu√© el error no se puede entregar a <code>onError</code> . <br><br>  Los casos en que esto puede suceder dependen de lo que las fuentes y los suscriptores hagan espec√≠ficamente.  Consideraremos los ejemplos a continuaci√≥n, pero en general podemos decir que tal error ocurre si no hay un suscriptor activo a quien se le pueda entregar el error. <br><br><h3>  Ejemplo con zipWith () </h3><br>  La primera opci√≥n en la que puede generar una <code>zipWith</code> es la <code>zipWith</code> . <br><br><pre> <code class="kotlin hljs"><span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable1 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable2 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> zipper = BiFunction&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, String&gt; { one, two -&gt; <span class="hljs-string"><span class="hljs-string">"</span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$one</span></span></span><span class="hljs-string"> - </span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$two</span></span></span><span class="hljs-string">"</span></span> } observable1.zipWith(observable2, zipper) .subscribe( { System.<span class="hljs-keyword"><span class="hljs-keyword">out</span></span>.println(it) }, { it.printStackTrace() } )</code> </pre><br>  Combinamos dos fuentes juntas, cada una de las cuales causa un error.  Que esperamos  Podemos suponer que <code>onError</code> se llamar√° dos veces, pero esto contradice <a href="">la especificaci√≥n de</a> <code>Reactive streams</code> . <br><blockquote>  Despu√©s de una sola llamada a un evento de terminal ( <code>onError</code> , <code>onCompelete</code> ), se requiere que no se realicen m√°s llamadas <br></blockquote><br>  Resulta que con una sola llamada a <code>onError</code> segunda llamada ya no es posible.  ¬øQu√© sucede cuando se produce un segundo error en la fuente?  Se entregar√° a <code>RxJavaPlugins.onError</code> . <br><br>  Una manera f√°cil de entrar en esta situaci√≥n es usar <code>zip</code> para combinar llamadas de red (por ejemplo, dos llamadas de <code>Retrofit</code> devuelven <code>Observable</code> ).  Si se produce un error en ambas llamadas (por ejemplo, no hay conexi√≥n a Internet), ambas fuentes causar√°n errores, el primero de los cuales caer√° en la implementaci√≥n <code>onError</code> y el segundo se entregar√° al controlador de errores base ( <code>RxJavaPlugins.onError</code> ). <br><br><h3>  Ejemplo de ConnectableObservable sin suscriptores </h3><br>  <code>ConnectableObservable</code> tambi√©n puede generar una <code>UndeliverableException</code> .  Vale la pena recordar que <code>ConnectableObservable</code> genera eventos independientemente de la presencia de suscriptores activos, solo llame al m√©todo <code>connect()</code> .  Si se produce un error en <code>ConnectableObservable</code> cuando no hay suscriptores, se entregar√° al controlador de errores base. <br><br>  Aqu√≠ hay un ejemplo bastante inocente que podr√≠a causar tal error: <br><br><pre> <code class="kotlin hljs">someApi.retrofitCall() <span class="hljs-comment"><span class="hljs-comment">//     Retrofit .publish() .connect()</span></span></code> </pre><br>  Si <code>someApi.retrofitCall()</code> causa un error (por ejemplo, no hay conexi√≥n a Internet), la aplicaci√≥n se bloquear√° porque el error de red se entregar√° al <code>RxJava</code> errores base <code>RxJava</code> . <br><br>  Este ejemplo parece ficticio, pero es muy f√°cil entrar en una situaci√≥n en la que <code>ConnectableObservable</code> todav√≠a est√° conectado, pero no tiene suscriptores.  Me encontr√© con esto al usar <code>autoConnect()</code> al llamar a una API.  <code>autoConnect()</code> no deshabilita autom√°ticamente <code>Observable</code> .  Me <code>onStop</code> en el m√©todo de <code>Activity</code> <code>onStop</code> , pero el resultado de la llamada de red regres√≥ despu√©s de la destrucci√≥n de la <code>Activity</code> y la aplicaci√≥n se <code>UndeliverableException</code> con <code>UndeliverableException</code> . <br><br><h3>  Manejo de errores </h3><br>  Entonces, ¬øqu√© hacer con estos errores? <br><br>  El primer paso es observar los errores que ocurren e intentar determinar qu√© los causa.  Idealmente, si puede solucionar el problema en su origen para evitar que el error se <code>RxJavaPlugins.onError</code> a <code>RxJavaPlugins.onError</code> . <br><br>  La soluci√≥n para el ejemplo <code>zipWith</code> es tomar una o ambas fuentes e implementar <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">uno de los m√©todos</a> para detectar errores en ellas.  Por ejemplo, puede usar <code>onErrorReturn</code> para pasar el valor predeterminado en lugar de un error. <br><br>  El ejemplo de <code>ConnectableObservable</code> es m√°s sencillo de solucionar, solo aseg√∫rese de desconectar <code>Observable</code> cuando el √∫ltimo suscriptor se da de baja.  <code>autoConnect()</code> , por ejemplo, tiene una implementaci√≥n sobrecargada que toma una funci√≥n que captura el tiempo de conexi√≥n ( <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=es&amp;u=">se puede ver m√°s aqu√≠</a> ). <br><br>  Otra forma de resolver el problema es reemplazar el controlador de errores base por el suyo.  El <code>RxJavaPlugins.setErrorHandler(Consumer&lt;Throwable&gt;)</code> lo ayudar√° con esto.  Si esta es la soluci√≥n adecuada para usted, puede detectar todos los errores enviados a <code>RxJavaPlugins.onError</code> y manejarlos como mejor le parezca.  Esta soluci√≥n puede ser bastante complicada: recuerde que <code>RxJavaPlugins.onError</code> recibe errores de todas <code>RxJava</code> transmisiones de <code>RxJava</code> en la aplicaci√≥n. <br><br>  Si crea manualmente su <code>Observable</code> , puede llamar a <code>emitter.tryOnError()</code> lugar de <code>emitter.tryOnError()</code> .  Este m√©todo informa un error solo si la transmisi√≥n no finaliza y tiene suscriptores.  Recuerda que este m√©todo es experimental. <br><br>  La moraleja de este art√≠culo es que no puede estar seguro de que no haya errores al trabajar con RxJava si simplemente implement√≥ <code>onError</code> en los suscriptores.  Debe tener en cuenta las situaciones en las que los errores pueden no estar disponibles para los suscriptores y asegurarse de que se manejan estas situaciones. </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/es422611/">https://habr.com/ru/post/es422611/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../es422597/index.html">Backend United # 2: Relleno</a></li>
<li><a href="../es422601/index.html">Chrome 69 sale con un generador de contrase√±as aleatorias</a></li>
<li><a href="../es422603/index.html">Un poco m√°s cerca de la perfecci√≥n</a></li>
<li><a href="../es422605/index.html">Cultivar una caja fuerte desde temprana edad: programa educativo de Rostelecom y MIPT</a></li>
<li><a href="../es422609/index.html">Barrera del lenguaje y PNL. ¬øPor qu√© los chatbots no nos entienden?</a></li>
<li><a href="../es422613/index.html">El cibergrupo PowerPool domin√≥ la vulnerabilidad de d√≠a cero en la llamada de procedimiento local avanzado</a></li>
<li><a href="../es422615/index.html">Toda la verdad sobre RTOS. Art√≠culo # 9. Programador: implementaci√≥n</a></li>
<li><a href="../es422617/index.html">Toda la verdad sobre RTOS. Art√≠culo # 8. Nucleus SE: dise√±o interno y despliegue</a></li>
<li><a href="../es422623/index.html">C√≥mo asegurar C</a></li>
<li><a href="../es422625/index.html">Hablamos con Troy Miles, el programador de "Neuromancer"</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>