<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>üå± ü§© üöÆ Python-Ausnahmen gelten jetzt als Anti-Pattern üÜô üë∂ üëú</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Was sind Ausnahmen? Aus dem Namen geht hervor, dass sie auftreten, wenn im Programm eine Ausnahme auftritt. Sie fragen sich vielleicht, warum Ausnahme...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Python-Ausnahmen gelten jetzt als Anti-Pattern</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/oleg-bunin/blog/445234/">  Was sind Ausnahmen?  Aus dem Namen geht hervor, dass sie auftreten, wenn im Programm eine Ausnahme auftritt.  Sie fragen sich vielleicht, warum Ausnahmen ein Anti-Muster sind und in welcher Beziehung sie zur Eingabe stehen.  Ich habe versucht, <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">es herauszufinden</a> , und jetzt m√∂chte ich das mit Ihnen besprechen, harazhiteli. <br><br><h2>  Ausnahmeprobleme </h2><br>  Es ist schwer, Fehler in dem zu finden, mit denen Sie jeden Tag konfrontiert sind.  Gewohnheit und Blindheit verwandeln Fehler in Merkmale, aber versuchen wir, Ausnahmen offen zu betrachten. <br><br><h3>  Ausnahmen sind schwer zu erkennen </h3><br>  Es gibt zwei Arten von Ausnahmen: "explizit" wird durch Aufrufen von " <code>raise</code> direkt in dem Code erstellt, den Sie gerade lesen.  "Versteckt" sind in den verwendeten Funktionen, Klassen, Methoden versteckt. <br><br>  Das Problem ist, dass die "versteckten" Ausnahmen wirklich schwer zu bemerken sind.  Lassen Sie mich Ihnen ein Beispiel f√ºr eine reine Funktion zeigen: <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second</code> </pre><br>  Die Funktion teilt einfach eine Zahl durch eine andere und gibt einen <code>float</code> .  Die Typen werden √ºberpr√ºft und Sie k√∂nnen Folgendes ausf√ºhren: <br><br><pre> <code class="python hljs">result = divide(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>) print(<span class="hljs-string"><span class="hljs-string">'x / y = '</span></span>, result)</code> </pre><br>  Hast du es bemerkt?  Tats√§chlich wird die Ausf√ºhrung des Programms niemals den <code>print</code> erreichen, da das Teilen von 1 durch 0 eine unm√∂gliche Operation ist und einen <code>ZeroDivisionError</code> .  Ja, ein solcher Code ist typsicher, kann aber trotzdem nicht verwendet werden. <br><a name="habracut"></a><br>  Um ein potenzielles Problem auch in einem so einfachen und lesbaren Code zu bemerken, braucht man Erfahrung.  Alles in Python kann aufh√∂ren, mit verschiedenen Arten von Ausnahmen zu arbeiten: Division, Funktionsaufrufe, <code>int</code> , <code>str</code> , Generatoren, Iteratoren in Schleifen, Zugriff auf Attribute oder Schl√ºssel.  Sogar <code>raise something()</code> kann einen Absturz verursachen.  Au√üerdem erw√§hne ich nicht einmal Eingabe- und Ausgabeoperationen.  Und <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">gepr√ºfte Ausnahmen werden</a> in naher Zukunft <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">nicht mehr unterst√ºtzt</a> . <br><br><h3>  Die Wiederherstellung des normalen Verhaltens ist nicht m√∂glich </h3><br>  Aber genau f√ºr einen solchen Fall haben wir Ausnahmen.  Lassen Sie uns einfach <code>ZeroDivisionError</code> und der Code wird typsicher. <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second <span class="hljs-keyword"><span class="hljs-keyword">except</span></span> ZeroDivisionError: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-number"><span class="hljs-number">0.0</span></span></code> </pre><br>  Jetzt ist alles in Ordnung.  Aber warum geben wir 0 zur√ºck?  Warum nicht 1 oder <code>None</code> ?  Nat√ºrlich ist es in den meisten F√§llen fast so schlecht (wenn nicht sogar noch schlimmer), <code>None</code> , aber Sie m√ºssen sich dennoch auf die Gesch√§ftslogik und die Optionen verlassen, um die Funktion verwenden zu k√∂nnen. <br><br>  Was genau teilen wir?  Beliebige Zahlen, bestimmte Einheiten oder Geld?  Nicht jede Option ist leicht vorherzusehen und wiederherzustellen.  Es kann sich herausstellen, dass Sie bei der n√§chsten Verwendung einer Funktion eine andere Wiederherstellungslogik ben√∂tigen. <br><br><blockquote>  Die traurige Schlussfolgerung: Die L√∂sung f√ºr jedes Problem ist individuell, abh√§ngig vom spezifischen Anwendungskontext. </blockquote><br>  Es gibt keine Silberkugel, die sich ein f√ºr alle Mal mit <code>ZeroDivisionError</code> .  Und wir sprechen nicht √ºber die M√∂glichkeit komplexer E / A mit wiederholten Anforderungen und Zeit√ºberschreitungen. <br><br>  Vielleicht ist es nicht notwendig, Ausnahmen genau dort zu behandeln, wo sie auftreten?  Vielleicht werfen Sie es einfach in den Code-Ausf√ºhrungsprozess - jemand wird es sp√§ter herausfinden.  Und dann sind wir gezwungen, zum aktuellen Stand der Dinge zur√ºckzukehren. <br><br><h3>  Ausf√ºhrungsprozess unklar </h3><br>  Hoffen wir, dass jemand anderes die Ausnahme abf√§ngt und sie m√∂glicherweise behandelt.  Beispielsweise kann das System den Benutzer auffordern, den eingegebenen Wert zu √§ndern, da er nicht durch 0 geteilt werden kann. Die <code>divide</code> sollte nicht explizit f√ºr die Behebung des Fehlers verantwortlich sein. <br><br>  In diesem Fall m√ºssen Sie √ºberpr√ºfen, wo wir die Ausnahme abgefangen haben.  Wie kann man √ºbrigens genau bestimmen, wo es verarbeitet wird?  Ist es m√∂glich, an die richtige Stelle im Code zu gelangen?  Es stellt sich heraus, dass <strong>es unm√∂glich ist</strong> . <br><br>  Es ist nicht m√∂glich zu bestimmen, welche Codezeile ausgef√ºhrt wird, nachdem die Ausnahme ausgel√∂st wurde.  Verschiedene Arten von Ausnahmen k√∂nnen mit unterschiedlichen <code>except</code> , und einige Ausnahmen k√∂nnen <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">ignoriert werden</a> .  Sie k√∂nnen zus√§tzliche Ausnahmen in anderen Modulen ausl√∂sen, die fr√ºher ausgef√ºhrt werden und im Allgemeinen die gesamte Logik besch√§digen. <br><br>  Angenommen, eine Anwendung enth√§lt zwei unabh√§ngige Threads: einen regul√§ren Thread, der von oben nach unten ausgef√ºhrt wird, und einen Ausnahmethread, der nach Belieben ausgef√ºhrt wird.  Wie kann man diesen Code lesen und verstehen? <br><br>  Nur bei eingeschaltetem Debugger im Modus "Alle Ausnahmen abfangen". <br><br><div style="text-align:center;"><img src="https://habrastorage.org/webt/8k/bn/do/8kbndolwukkaluarfk3vpexws2w.png"></div><br>  Ausnahmen wie das ber√ºchtigte <code>goto</code> rei√üen die Programmstruktur auf. <br><br><h3>  Ausnahmen sind nicht exklusiv </h3><br>  Schauen wir uns ein anderes Beispiel an: den √ºblichen Remote-HTTP-API-Zugangscode: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> requests <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">fetch_user_profile</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(user_id: int)</span></span></span><span class="hljs-function"> -&gt; 'UserProfile':</span></span> <span class="hljs-string"><span class="hljs-string">"""Fetches UserProfile dict from foreign API."""</span></span> response = requests.get(<span class="hljs-string"><span class="hljs-string">'/api/users/{0}'</span></span>.format(user_id)) response.raise_for_status() <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> response.json()</code> </pre><br>  In diesem Beispiel kann buchst√§blich alles schief gehen.  Hier ist eine unvollst√§ndige Liste m√∂glicher Fehler: <br><br><ul><li>  Das Netzwerk ist m√∂glicherweise nicht verf√ºgbar und die Anforderung wird √ºberhaupt nicht ausgef√ºhrt. </li><li>  Der Server funktioniert m√∂glicherweise nicht. </li><li>  Der Server ist m√∂glicherweise zu ausgelastet. Es tritt eine Zeit√ºberschreitung auf. </li><li>  Der Server erfordert m√∂glicherweise eine Authentifizierung. </li><li>  Eine API verf√ºgt m√∂glicherweise nicht √ºber eine solche URL. </li><li>  Ein nicht existierender Benutzer kann √ºbertragen werden. </li><li>  M√∂glicherweise nicht genug Rechte. </li><li>  Der Server kann aufgrund eines internen Fehlers w√§hrend der Verarbeitung Ihrer Anfrage abst√ºrzen </li><li>  Der Server gibt m√∂glicherweise eine ung√ºltige oder besch√§digte Antwort zur√ºck. </li><li>  Der Server gibt m√∂glicherweise ung√ºltigen JSON zur√ºck, der nicht analysiert werden kann. </li></ul><br>  Die Liste geht weiter und weiter, so viele potenzielle Probleme liegen im Code der ungl√ºcklichen drei Zeilen.  Wir k√∂nnen sagen, dass es im Allgemeinen nur durch einen gl√ºcklichen Zufall funktioniert und mit einer Ausnahme viel wahrscheinlicher f√§llt. <br><br><h2>  Wie k√∂nnen Sie sich sch√ºtzen? </h2><br>  Nachdem wir sichergestellt haben, dass Ausnahmen den Code sch√§digen k√∂nnen, wollen wir herausfinden, wie Sie sie entfernen k√∂nnen.  Um ausnahmslos Code zu schreiben, gibt es verschiedene Muster. <br><br><ul><li>  √úberall schreiben <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">except Exception: pass</a></code> .  Sackgasse.  <strong>Tu das nicht.</strong> </li><li>  <code>None</code> .  Zu b√∂se.  Infolgedessen m√ºssen Sie entweder fast jede Zeile mit beginnen, <code>if something is not None:</code> und die gesamte Logik geht hinter dem M√ºll der Bereinigungspr√ºfungen verloren, oder Sie leiden die ganze Zeit unter <code>TypeError</code> .  Keine gute Wahl. </li><li>  Schreiben Sie Klassen f√ºr spezielle Anwendungsf√§lle.  Zum Beispiel die Basisklasse <code>User</code> mit Unterklassen f√ºr Fehler wie <code>UserNotFound</code> und <code>MissingUser</code> .  Dieser Ansatz kann in bestimmten Situationen verwendet werden, z. B. in <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">AnonymousUser</a></code> in Django. Das Umschlie√üen aller m√∂glichen Fehler in Klassen ist jedoch unrealistisch.  Es wird zu viel Arbeit erfordern und das Dom√§nenmodell wird unvorstellbar komplex. </li><li>  Verwenden Sie Container, um die resultierende Variable oder den Fehlerwert in einen Wrapper zu verpacken, und arbeiten Sie weiter mit dem Containerwert.  Aus diesem Grund haben wir das Projekt <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">@dry-python/return</a></code> .  Diese Funktionen geben also etwas Sinnvolles, Typisiertes und Sicheres zur√ºck. </li></ul><br>  Kehren wir zum Divisionsbeispiel zur√ºck, das im Fehlerfall 0 zur√ºckgibt. K√∂nnen wir explizit angeben, dass die Funktion ohne R√ºckgabe eines bestimmten numerischen Werts nicht erfolgreich war? <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; Result[float, ZeroDivisionError]:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Success(first / second) <span class="hljs-keyword"><span class="hljs-keyword">except</span></span> ZeroDivisionError <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> exc: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Failure(exc)</code> </pre><br>  Wir schlie√üen die Werte in einen von zwei Wrappern ein: <code>Success</code> oder <code>Failure</code> .  Diese Klassen werden von der <code>Result</code> Basisklasse geerbt.  Arten von gepackten Werten k√∂nnen in der Anmerkung mit der zur√ºckgegebenen Funktion angegeben werden, z. B. <code>Result[float, ZeroDivisionError]</code> gibt entweder <code>Success[float]</code> oder <code>Failure[ZeroDivisionError]</code> . <br><br>  Was gibt uns das?  Weitere <strong>Ausnahmen sind keine Ausnahme, aber erwartete Probleme</strong> .  Das Umschlie√üen einer Ausnahme in <code>Failure</code> l√∂st au√üerdem ein zweites Problem: die Komplexit√§t der Identifizierung potenzieller Ausnahmen. <br><br><pre> <code class="python hljs"><span class="hljs-number"><span class="hljs-number">1</span></span> + divide(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>) <span class="hljs-comment"><span class="hljs-comment"># =&gt; mypy error: Unsupported operand types for + ("int" and "Result[float, ZeroDivisionError]")</span></span></code> </pre><br>  Jetzt sind sie leicht zu erkennen.  Wenn im Code <code>Result</code> angezeigt wird, l√∂st die Funktion m√∂glicherweise eine Ausnahme aus.  Und Sie kennen seinen Typ sogar im Voraus. <br><br>  Dar√ºber hinaus ist die Bibliothek vollst√§ndig typisiert und <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">mit PEP561 kompatibel</a> .  Das hei√üt, mypy warnt Sie, wenn Sie versuchen, etwas zur√ºckzugeben, das nicht dem deklarierten Typ entspricht. <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; Result[float, ZeroDivisionError]:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Success(<span class="hljs-string"><span class="hljs-string">'Done'</span></span>) <span class="hljs-comment"><span class="hljs-comment"># =&gt; error: incompatible type "str"; expected "float" except ZeroDivisionError as exc: return Failure(0) # =&gt; error: incompatible type "int"; expected "ZeroDivisionError"</span></span></code> </pre><br><h3>  Wie arbeite ich mit Containern? </h3><br>  Es gibt zwei <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">Methoden</a> : <br><br><ul><li>  <code>map</code> f√ºr Funktionen, die normale Werte zur√ºckgeben; </li><li>  <code>bind</code> f√ºr Funktionen, die andere Container zur√ºckgeben. </li></ul><br><pre> <code class="python hljs">Success(<span class="hljs-number"><span class="hljs-number">4</span></span>).bind(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number / <span class="hljs-number"><span class="hljs-number">2</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Success(2) Success(4).map(lambda number: number + 1) # =&gt; Success(5)</span></span></code> </pre><br>  Das Sch√∂ne ist, dass dieser Code Sie vor erfolglosen Skripten <code>.bind</code> , da <code>.bind</code> und <code>.map</code> f√ºr Container mit <code>Failure</code> nicht ausgef√ºhrt werden: <br><br><pre> <code class="python hljs">Failure(<span class="hljs-number"><span class="hljs-number">4</span></span>).bind(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number / <span class="hljs-number"><span class="hljs-number">2</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Failure(4) Failure(4).map(lambda number: number / 2) # =&gt; Failure(4)</span></span></code> </pre><br>  Jetzt k√∂nnen Sie sich nur noch auf den richtigen Ausf√ºhrungsprozess konzentrieren und sicherstellen, dass der falsche Status das Programm nicht an einem unerwarteten Ort besch√§digt.  Und es besteht immer die M√∂glichkeit, <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">den falschen Zustand festzustellen, zu korrigieren</a> und zum beabsichtigten Pfad des Prozesses zur√ºckzukehren. <br><br><pre> <code class="python hljs">Failure(<span class="hljs-number"><span class="hljs-number">4</span></span>).rescue(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number + <span class="hljs-number"><span class="hljs-number">1</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Success(5) Failure(4).fix(lambda number: number / 2) # =&gt; Success(2)</span></span></code> </pre><br>  In unserem Ansatz werden ‚Äûalle Probleme einzeln gel√∂st‚Äú und ‚Äûder Ausf√ºhrungsprozess ist jetzt transparent‚Äú.  Viel Spa√ü beim Programmieren auf Schienen! <br><br><h3>  Aber wie kann man Werte aus Containern erweitern? </h3><br>  Wenn Sie mit Funktionen arbeiten, die nichts √ºber Container wissen, ben√∂tigen Sie die Werte selbst.  Dann k√∂nnen Sie die <code>.unwrap()</code> oder <code>.value_or()</code> verwenden: <br><br><pre> <code class="python hljs">Success(<span class="hljs-number"><span class="hljs-number">1</span></span>).unwrap() <span class="hljs-comment"><span class="hljs-comment"># =&gt; 1 Success(0).value_or(None) # =&gt; 0 Failure(0).value_or(None) # =&gt; None Failure(1).unwrap() # =&gt; Raises UnwrapFailedError()</span></span></code> </pre><br>  Warten Sie, wir mussten die Ausnahmen <code>.unwrap()</code> , und jetzt stellt sich heraus, dass alle <code>.unwrap()</code> -Aufrufe zu einer anderen Ausnahme f√ºhren k√∂nnen? <br><br><h3>  Wie man nicht an UnwrapFailedErrors denkt? </h3><br>  Ok, mal sehen, wie man mit den neuen Ausnahmen lebt.  Betrachten Sie dieses Beispiel: Sie m√ºssen Benutzereingaben √ºberpr√ºfen und zwei Modelle in der Datenbank erstellen.  Jeder Schritt kann mit einer Ausnahme enden, weshalb alle Methoden in <code>Result</code> : <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> <span class="hljs-comment"><span class="hljs-comment"># </span><span class="hljs-doctag"><span class="hljs-comment"><span class="hljs-doctag">TODO:</span></span></span><span class="hljs-comment"> we need to create a pipeline of these methods somehow... def _validate_user( self, username: str, email: str, ) -&gt; Result['UserSchema', str]: """Returns an UserSchema for valid input, otherwise a Failure.""" def _create_account( self, user_schema: 'UserSchema', ) -&gt; Result['Account', str]: """Creates an Account for valid UserSchema's. Or returns a Failure.""" def _create_user( self, account: 'Account', ) -&gt; Result['User', str]: """Create an User instance. If user already exists returns Failure."""</span></span></code> </pre><br>  Erstens m√ºssen Sie die Werte in Ihrer eigenen Gesch√§ftslogik √ºberhaupt nicht erweitern: <br><br><pre> <code class="python hljs"><span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">__call__</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, username: str, email: str)</span></span></span><span class="hljs-function"> -&gt; Result['User', str]:</span></span> <span class="hljs-string"><span class="hljs-string">"""Can return a Success(user) or Failure(str_reason)."""</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> self._validate_user( username, email, ).bind( self._create_account, ).bind( self._create_user, ) <span class="hljs-comment"><span class="hljs-comment"># ...</span></span></code> </pre><br>  Alles wird ohne Probleme funktionieren, es werden keine Ausnahmen <code>.unwrap()</code> , da <code>.unwrap()</code> nicht verwendet wird.  Aber ist es einfach, solchen Code zu lesen?  Nein.  Und was ist die Alternative?  <code>@pipeline</code> : <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> result.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> pipeline <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> @pipeline <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">__call__</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, username: str, email: str)</span></span></span><span class="hljs-function"> -&gt; Result['User', str]:</span></span> <span class="hljs-string"><span class="hljs-string">"""Can return a Success(user) or Failure(str_reason)."""</span></span> user_schema = self._validate_user(username, email).unwrap() account = self._create_account(user_schema).unwrap() <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> self._create_user(account) <span class="hljs-comment"><span class="hljs-comment"># ...</span></span></code> </pre><br>  Jetzt ist dieser Code gut gelesen.  So arbeiten <code>.unwrap()</code> und <code>@pipeline</code> zusammen: Wenn eine <code>.unwrap()</code> -Methode fehlschl√§gt und <code>Failure[str]</code> , wird sie vom <code>@pipeline</code> Dekorateur <code>@pipeline</code> und gibt <code>Failure[str]</code> als resultierenden Wert zur√ºck.  Auf diese Weise schlage ich vor, alle Ausnahmen aus dem Code zu entfernen und ihn wirklich sicher und typisiert zu machen. <br><br><h2>  Wickeln Sie alles zusammen </h2><br>  Nun wenden wir die neuen Tools beispielsweise mit einer Anfrage an die HTTP-API an.  Denken Sie daran, dass jede Zeile eine Ausnahme ausl√∂sen kann?  Und es gibt keine M√∂glichkeit, sie dazu zu bringen, den Container mit <code>Result</code> .  Sie k√∂nnen den <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">@safe-Dekorator jedoch verwenden</a> , um unsichere Funktionen zu verpacken und sicher zu machen.  Im Folgenden finden Sie zwei Codeoptionen, die dasselbe tun: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> safe @safe <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second <span class="hljs-comment"><span class="hljs-comment"># is the same as: def divide(first: float, second: float) -&gt; Result[float, ZeroDivisionError]: try: return Success(first / second) except ZeroDivisionError as exc: return Failure(exc)</span></span></code> </pre><br>  Die erste mit <code>@safe</code> ist einfacher und besser zu lesen. <br><br>  Das letzte, was Sie im API-Anforderungsbeispiel tun m√ºssen, ist das Hinzuf√ºgen des <code>@safe</code> Dekorators.  Das Ergebnis ist der folgende Code: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> requests <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> pipeline, safe <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">FetchUserProfile</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Single responsibility callable object that fetches user profile."""</span></span> <span class="hljs-comment"><span class="hljs-comment">#: You can later use dependency injection to replace `requests` #: with any other http library (or even a custom service). _http = requests @pipeline def __call__(self, user_id: int) -&gt; Result['UserProfile', Exception]: """Fetches UserProfile dict from foreign API.""" response = self._make_request(user_id).unwrap() return self._parse_json(response) @safe def _make_request(self, user_id: int) -&gt; requests.Response: response = self._http.get('/api/users/{0}'.format(user_id)) response.raise_for_status() return response @safe def _parse_json(self, response: requests.Response) -&gt; 'UserProfile': return response.json()</span></span></code> </pre><br>  <strong>So fassen Sie zusammen, wie Sie Ausnahmen beseitigen und den Code sichern k√∂nnen</strong> : <br><br><ul><li>  Verwenden Sie den <code>@safe</code> Wrapper f√ºr alle Methoden, die eine Ausnahme <code>@safe</code> k√∂nnen.  Der R√ºckgabetyp der Funktion wird in <code>Result[OldReturnType, Exception]</code> . </li><li>  Verwenden Sie <code>Result</code> als Container, um Werte und Fehler in eine einfache Abstraktion zu √ºbertragen. </li><li>  Verwenden Sie <code>.unwrap()</code> , um den Wert aus dem Container zu erweitern. </li><li>  Verwenden Sie <code>@pipeline</code> , um das <code>.unwrap</code> <code>@pipeline</code> <code>.unwrap</code> vereinfachen. </li></ul><br>  Durch die Einhaltung dieser Regeln k√∂nnen wir genau das Gleiche tun - nur sicher und gut lesbar.  Alle Probleme mit Ausnahmen wurden behoben: <br><br><ul><li>  <strong>"Ausnahmen sind schwer zu erkennen</strong> . <strong>"</strong>  Jetzt werden sie in einen typisierten <code>Result</code> eingewickelt, wodurch sie vollst√§ndig transparent sind. </li><li>  <strong>"Die Wiederherstellung eines normalen Verhaltens ist unm√∂glich</strong> . <strong>"</strong>  Jetzt k√∂nnen Sie den Wiederherstellungsprozess sicher an den Anrufer delegieren.  F√ºr einen solchen Fall gibt es <code>.fix()</code> und <code>.rescue()</code> . </li><li>  <strong>"Die Reihenfolge der Ausf√ºhrung ist unklar</strong> . <strong>"</strong>  Jetzt sind sie eins mit dem √ºblichen Gesch√§ftsfluss.  Von Anfang bis Ende. </li><li>  <strong>"Ausnahmen sind keine Ausnahme</strong> . <strong>"</strong>  Wir wissen!  Und wir erwarten, dass etwas schief geht und zu allem bereit ist. </li></ul><br><h3>  Anwendungsf√§lle und Einschr√§nkungen </h3><br>  Offensichtlich k√∂nnen Sie diesen Ansatz nicht in Ihrem gesamten Code verwenden.  Es ist f√ºr die meisten allt√§glichen Situationen <strong>zu sicher</strong> und mit anderen Bibliotheken oder Frameworks nicht kompatibel.  Sie m√ºssen jedoch die wichtigsten Teile Ihrer Gesch√§ftslogik genau so schreiben, wie ich es gezeigt habe, um den ordnungsgem√§√üen Betrieb Ihres Systems sicherzustellen und den zuk√ºnftigen Support zu erleichtern. <br><br><blockquote>  Bringt Sie das Thema zum Nachdenken oder scheint es sogar heilig zu sein?  Kommen Sie am 5. April nach <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">Moskau Python Conf ++</a> , wir werden diskutieren!  Neben mir wird Artyom Malyshev, der Gr√ºnder des Dry-Python-Projekts und Kernentwickler von Django Channels, dort sein.  Er <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">wird</a> mehr √ºber Dry Python und Gesch√§ftslogik <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">sprechen</a> . </blockquote></div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/de445234/">https://habr.com/ru/post/de445234/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../de445220/index.html">AMD Radeon VII: High-End-Chip (Teil 3)</a></li>
<li><a href="../de445222/index.html">Erhalten Sie innerhalb eines Tages ein Angebot an das Backend-Team am Cosmonautics Day</a></li>
<li><a href="../de445226/index.html">Die Entwicklung einer Rakete, die den Mond erreichen kann, wird Russland 740 Milliarden Rubel kosten</a></li>
<li><a href="../de445228/index.html">Kryptographie in Java. Mac-Klasse</a></li>
<li><a href="../de445230/index.html">Die Registrierung f√ºr die II IT-Konferenz f√ºr Anf√§nger SMARTRHINO-2019 begann</a></li>
<li><a href="../de445236/index.html">"Extreme NOW Forum 2019": Registrierung offen</a></li>
<li><a href="../de445238/index.html">Wachsen Sie gro√ü: Top 10 Berichte von Mobius 2018 Moskau</a></li>
<li><a href="../de445240/index.html">Wie kann man sehr gro√üe Daten kosteng√ºnstig und schnell verschieben, hochladen und integrieren? Was ist Pushdown-Optimierung?</a></li>
<li><a href="../de445242/index.html">Erfahrung mit Coroutinen und Retrofit2</a></li>
<li><a href="../de445244/index.html">"Geldspiele au√üerhalb der Blockchain m√ºssen sterben"</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>