<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>👌🏻 🎅🏽 🍳 RxJava2中的标准错误处理程序，或者即使实现了onError，RxJava为何导致应用程序崩溃的原因 🧕🏻 🍉 💪🏻</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="本文将讨论RxJava2 2.0.6版和更高版本中的UndeliverableException 。 如果有人相撞而无法解决，或者根本听不到这个问题-我要一只猫。 从RxJava1过渡到RxJava1后，他们促使翻译production的问题。 原文写于2017年12月28日，但总比没有发现要晚。 ...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>RxJava2中的标准错误处理程序，或者即使实现了onError，RxJava为何导致应用程序崩溃的原因</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/post/422611/">本文将讨论<code>RxJava2</code> <code>2.0.6</code>版和更高版本中的<code>UndeliverableException</code> 。 如果有人相撞而无法解决，或者根本听不到这个问题-我要一只猫。 从<code>RxJava1</code>过渡到<code>RxJava1</code>后，他们促使翻译<code>production</code>的问题。 原文写于2017年12月28日，但总比没有发现要晚。 <br><div style="text-align:center;"><img src="https://habrastorage.org/webt/sh/49/yi/sh49yi0mhl6-tmfir_fdvlkmcny.png"></div><a name="habracut"></a> 我们都是优秀的开发人员，使用<code>RxJava</code>时会在<code>onError</code>捕获错误。 这意味着我们已经保护自己免受应用程序崩溃的侵害，对吗？ <br><br>  <i>不，不是真的。</i> <br><br> 下面我们将看几个示例，其中即使正确实现了<code>onError</code> ，应用程序也会由于<code>RxJava</code>而<code>RxJava</code> 。 <br><br><h3>  <code>RxJava</code>基本错误处理<code>RxJava</code> </h3><br>  <code>RxJava</code>使用<code>RxJavaPlugins.onError</code>作为基本错误处理程序。 它处理所有无法传递给订户的错误。 默认情况下，所有错误都会发送给它，因此可能会导致严重的应用程序崩溃。 <br>  <a href=""><code>    2.0.6</code></a>描述了此行为： <br><blockquote>  2.x设计的目标之一是没有丢失的错误。 有时序列在源引发<code>onError</code>之前结束或被取消。 在这种情况下，错误无处可去，它被发送到<code>RxJavaPlugins.onError</code> <br></blockquote><br> 如果RxJava没有基本的错误处理程序，则此类错误将对我们隐藏，开发人员将对代码中的潜在问题一无所知。 <br><br> 从版本<code>2.0.6</code>开始， <code>RxJavaPlugins.onError</code>聪明，并共享库/实现错误以及无法传递错误的情况。 分配给“错误”类别的错误按原样调用，其余错误包装在<code>UndeliverableException</code> ，然后调用。 您可以<a href="">在这里</a>看到所有这些逻辑（ <code>onError</code>和<code>isBug</code> ）。 <br><br> 新手在<code>RxJava</code>的主要错误之一是<code>OnErrorNotImplementedException</code> 。 如果<code>observable</code>导致错误，并且订阅者中未实现<code>onError</code>方法，则会发生此错误。 该错误是一个错误的示例，对于基本错误处理程序<code>RxJava</code>是一个“错误”，并且不会变成<code>UndeliverableException</code> 。 <br><br><h3>  UndeliverableException </h3><br> 由于与“错误”相关的错误易于修复，因此我们不再赘述。  <code>RxJava</code>封装在<code>UndeliverableException</code>中的错误更为有趣，因为并非总是很明显为什么无法将错误传递给<code>onError</code> 。 <br><br> 发生这种情况的情况取决于来源和订户的具体操作。 我们将在下面考虑示例，但通常可以说，如果没有活动的订户可以将错误传递给用户，则会发生这种错误。 <br><br><h3>  zipWith（）的示例 </h3><br> 可以引发<code>UndeliverableException</code>的第一个选项是<code>zipWith</code> 。 <br><br><pre> <code class="kotlin hljs"><span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable1 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> observable2 = Observable.error&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>&gt;(Exception()) <span class="hljs-keyword"><span class="hljs-keyword">val</span></span> zipper = BiFunction&lt;<span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, <span class="hljs-built_in"><span class="hljs-built_in">Int</span></span>, String&gt; { one, two -&gt; <span class="hljs-string"><span class="hljs-string">"</span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$one</span></span></span><span class="hljs-string"> - </span><span class="hljs-variable"><span class="hljs-string"><span class="hljs-variable">$two</span></span></span><span class="hljs-string">"</span></span> } observable1.zipWith(observable2, zipper) .subscribe( { System.<span class="hljs-keyword"><span class="hljs-keyword">out</span></span>.println(it) }, { it.printStackTrace() } )</code> </pre><br> 我们将两个来源合并在一起，每个来源都会导致错误。 我们期望什么？ 我们可以假设<code>onError</code>将被调用两次，但这与<code>Reactive streams</code> <a href="">规范</a>相矛盾。 <br><blockquote> 在单次调用终端事件（ <code>onError</code> ， <code>onCompelete</code> ）之后，要求不再进行任何调用 <br></blockquote><br> 事实证明，通过单次调用<code>onError</code>不再可以<code>onError</code>第二次调用。 当源中发生第二个错误时会发生什么？ 它将被传递到<code>RxJavaPlugins.onError</code> 。 <br><br> 进入这种情况的一种简单方法是使用<code>zip</code>组合网络调用（例如，两个<code>Retrofit</code>调用返回<code>Observable</code> ）。 如果两个调用都发生错误（例如，没有Internet连接），则两个源都将导致错误，第一个将属于<code>onError</code>实现，第二个将传递给基本错误处理程序（ <code>RxJavaPlugins.onError</code> ）。 <br><br><h3> 没有订阅者的可连接示例 </h3><br>  <code>ConnectableObservable</code>也可以引发<code>UndeliverableException</code> 。 值得回顾的是，无论活动订户的存在与否， <code>ConnectableObservable</code>都会引发事件，只需调用<code>connect()</code>方法即可。 如果在没有订阅者的情况下<code>ConnectableObservable</code>发生错误，它将被传递给基本错误处理程序。 <br><br> 这是一个很纯真的例子，可能会导致这样的错误： <br><br><pre> <code class="kotlin hljs">someApi.retrofitCall() <span class="hljs-comment"><span class="hljs-comment">//     Retrofit .publish() .connect()</span></span></code> </pre><br> 如果<code>someApi.retrofitCall()</code>导致错误（例如，没有Internet连接），则应用程序将崩溃，因为网络错误将传递给<code>RxJava</code>基本错误<code>RxJava</code> 。 <br><br> 这个示例似乎是虚构的，但是很容易陷入<code>ConnectableObservable</code>仍处于连接状态但没有订阅者的情况。 我在调用API时使用<code>autoConnect()</code>时遇到了这个问题。  <code>autoConnect()</code>不会自动禁用<code>Observable</code> 。 我取消了<code>Activity</code>的<code>onStop</code>方法的订阅，但是在<code>Activity</code>销毁后应用程序因<code>UndeliverableException</code>而返回了网络调用的结果。 <br><br><h3> 错误处理 </h3><br> 那么如何处理这些错误呢？ <br><br> 第一步是查看发生的错误，并尝试确定导致这些错误的原因。 理想情况下，如果可以从<code>RxJavaPlugins.onError</code>解决问题，以防止将该错误<code>RxJavaPlugins.onError</code>给<code>RxJavaPlugins.onError</code> 。 <br><br>  <code>zipWith</code>示例的解决方案是采用一个或两个源，并实现<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=zh-CN&amp;u=">其中一种</a>捕获错误<a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=zh-CN&amp;u=">的方法</a> 。 例如，您可以使用<code>onErrorReturn</code>传递默认值而不是错误。 <br><br>  <code>ConnectableObservable</code>示例更易于修复-只要确保在最后一个订阅者退订时断开<code>Observable</code>的连接即可。 例如， <code>autoConnect()</code>有一个重载的实现，该实现带有捕获连接时间的函数（ <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=zh-CN&amp;u=">可以在此处查看更多信息</a> ）。 <br><br> 解决问题的另一种方法是用您自己的替换基本错误处理程序。  <code>RxJavaPlugins.setErrorHandler(Consumer&lt;Throwable&gt;)</code>方法将帮助您。 如果这是适合您的解决方案，则可以捕获所有发送到<code>RxJavaPlugins.onError</code>的错误，并根据需要进行处理。 该解决方案可能非常复杂-请记住， <code>RxJavaPlugins.onError</code>会从应用程序中的所有<code>RxJava</code>流接收错误。 <br><br> 如果您手动创建<code>Observable</code> ，则可以调用<code>emitter.tryOnError()</code>而不是<code>emitter.tryOnError()</code> 。 仅当流没有终止并且具有订阅者时，此方法才会报告错误。 请记住，此方法是实验性的。 <br><br> 本文的主旨是，如果仅在订阅服务器中实现<code>onError</code> ，则无法确定使用RxJava时没有错误。 您应该注意订户可能无法发现错误的情况，并确保已处理这些情况。 </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/zh-CN422611/">https://habr.com/ru/post/zh-CN422611/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../zh-CN422597/index.html">后端联合＃2：填充</a></li>
<li><a href="../zh-CN422601/index.html">Chrome 69随附随机密码生成器</a></li>
<li><a href="../zh-CN422603/index.html">更加接近完美</a></li>
<li><a href="../zh-CN422605/index.html">从小就开始种植保险箱-Rostelecom和MIPT的教育计划</a></li>
<li><a href="../zh-CN422609/index.html">语言障碍和NLP。 聊天机器人为什么不了解我们？</a></li>
<li><a href="../zh-CN422613/index.html">PowerPool网络组在高级本地过程调用中掌握了零日漏洞</a></li>
<li><a href="../zh-CN422615/index.html">关于RTOS的全部真相。 第9条。 调度程序：实施</a></li>
<li><a href="../zh-CN422617/index.html">关于RTOS的全部真相。 第8条 Nucleus SE：内部设计和部署</a></li>
<li><a href="../zh-CN422623/index.html">如何保护C</a></li>
<li><a href="../zh-CN422625/index.html">我们与“神经巫师”的程序员Troy Miles进行了交谈</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>