<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>👩🏾‍🔧 🔙 🤳🏼 Kotlin-Ausnahmen und ihre Merkmale ⛩️ 🕘 😐</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Unser Unternehmen setzt Kotlin seit mehr als zwei Jahren in der Produktion ein. Persönlich bin ich vor ungefähr einem Jahr auf diese Sprache gestoßen....">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Kotlin-Ausnahmen und ihre Merkmale</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/maxilect/blog/447380/">  Unser Unternehmen setzt Kotlin seit mehr als zwei Jahren in der Produktion ein.  Persönlich bin ich vor ungefähr einem Jahr auf diese Sprache gestoßen.  Es gibt viele Themen, über die gesprochen werden muss, aber heute werden wir über die Fehlerbehandlung sprechen, auch in einem funktionalen Stil.  Ich werde Ihnen sagen, wie das in Kotlin geht. <br><br><img src="https://habrastorage.org/webt/mb/bh/cp/mbbhcprsketr78wg8twpwhijg0y.jpeg" alt="Bild"><br><br>  <i>(Foto vom Treffen zu diesem Thema, das im Büro eines der Taganrog-Unternehmen stattfand. Alexey Shafranov, der Leiter der Arbeitsgruppe (Java) bei Maxilekt, sprach)</i> <br><a name="habracut"></a><br><h3>  Wie können Sie grundsätzlich mit Fehlern umgehen? </h3><br>  Ich habe verschiedene Wege gefunden: <br><br><ul><li>  Sie können einen <b>Rückgabewert</b> als Zeiger auf die Tatsache verwenden, dass ein Fehler vorliegt. </li><li>  Sie können <b>den Indikatorparameter</b> für denselben Zweck verwenden. </li><li>  Geben Sie eine <b>globale Variable ein</b> </li><li>  <b>Ausnahmen behandeln</b> </li><li>  <b>Verträge hinzufügen (DbC)</b> . </li></ul><br>  Lassen Sie uns näher auf jede der Optionen eingehen. <br><br><h4>  Rückgabewert </h4><br>  Ein bestimmter "magischer" Wert wird zurückgegeben, wenn ein Fehler auftritt.  Wenn Sie jemals Skriptsprachen verwendet haben, müssen Sie ähnliche Konstrukte gesehen haben. <br><br>  Beispiel 1: <br><br><pre><code class="plaintext hljs">function sqrt(x) { if(x &lt; 0) return -1; else return √x; }</code> </pre> <br>  Beispiel 2: <br><br><pre> <code class="plaintext hljs">function getUser(id) { result = db.getUserById(id) if (result) return result as User else return “Can't find user ” + id }</code> </pre><br><h4>  Indikatorparameter </h4><br>  Ein bestimmter Parameter, der an die Funktion übergeben wird, wird verwendet.  Nachdem Sie den Wert über den Parameter zurückgegeben haben, können Sie feststellen, ob in der Funktion ein Fehler aufgetreten ist. <br><br>  Ein Beispiel: <br><br><pre> <code class="plaintext hljs">function divide(x,y,out Success) { if (y == 0) Success = false else Success = true return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4>  Globale Variable </h4><br>  Die globale Variable funktioniert ungefähr genauso. <br><br>  Ein Beispiel: <br><br><pre> <code class="plaintext hljs">global Success = true function divide(x,y) { if (y == 0) Success = false else return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4>  Ausnahmen </h4><br>  Wir sind alle an Ausnahmen gewöhnt.  Sie werden fast überall eingesetzt. <br><br>  Ein Beispiel: <br><br><pre> <code class="plaintext hljs">function divide(x,y) { if (y == 0) throw Exception() else return x/y } try{ divide(10, 0)} catch (e) {//handle exception}</code> </pre><br><h4>  Verträge (DbC) </h4><br>  Ehrlich gesagt habe ich diesen Ansatz noch nie live gesehen.  Durch langes Googeln stellte ich fest, dass Kotlin 1.3 eine Bibliothek hat, die tatsächlich die Verwendung von Verträgen ermöglicht.  Das heißt,  Sie können Bedingungen für Variablen festlegen, die an die Funktion übergeben werden, Bedingungen für den Rückgabewert, die Anzahl der Aufrufe, von denen aus sie aufgerufen werden usw.  Und wenn alle Bedingungen erfüllt sind, wird angenommen, dass die Funktion korrekt funktioniert hat. <br><br>  Ein Beispiel: <br><br><pre> <code class="plaintext hljs">function sqrt (x) pre-condition (x &gt;= 0) post-condition (return &gt;= 0) begin calculate sqrt from x end</code> </pre><br>  Ehrlich gesagt hat diese Bibliothek eine schreckliche Syntax.  Vielleicht habe ich so etwas deshalb nicht live gesehen. <br><br><h3>  Ausnahmen in Java </h3><br>  Kommen wir zu Java und wie alles von Anfang an funktioniert hat. <br><br><img src="https://habrastorage.org/webt/gk/oo/mw/gkoomw72k7yp5mhpi9ebpt02g-i.png" alt="Bild"><br><br>  Beim Entwerfen einer Sprache wurden zwei Arten von Ausnahmen festgelegt: <br><br><ul><li>  geprüft - geprüft; </li><li>  deaktiviert - deaktiviert. </li></ul><br>  Wofür sind geprüfte Ausnahmen?  Theoretisch werden sie benötigt, damit die Leute nach Fehlern suchen müssen.  Das heißt,  Wenn eine bestimmte geprüfte Ausnahme möglich ist, muss sie später überprüft werden.  Theoretisch hätte dieser Ansatz dazu führen müssen, dass keine unverarbeiteten Fehler auftreten und die Codequalität verbessert wird.  In der Praxis ist dies jedoch nicht der Fall.  Ich denke, jeder hat mindestens einmal in seinem Leben einen leeren Fangblock gesehen. <br><br>  Warum kann das schlecht sein? <br><br>  Hier ist ein klassisches Beispiel direkt aus der Kotlin-Dokumentation - eine Schnittstelle aus dem in StringBuilder implementierten JDK: <br><br><pre> <code class="plaintext hljs">Appendable append(CharSequence csq) throws IOException; try { log.append(message) } catch (IOException e) { //Must be safe }</code> </pre><br>  Ich bin sicher, Sie haben eine Menge Code getroffen, der in try-catch eingeschlossen ist, wobei catch ein leerer Block ist, da eine solche Situation laut Entwickler einfach nicht hätte passieren dürfen.  In vielen Fällen wird die Behandlung geprüfter Ausnahmen folgendermaßen implementiert: Sie lösen einfach eine RuntimeException aus und fangen sie irgendwo darüber ab (oder fangen sie nicht ab ...). <br><br><pre> <code class="plaintext hljs">try { // do something } catch (IOException e) { throw new RuntimeException(e); //  - ...</code> </pre><br><h3>  Was ist in Kotlin möglich? </h3><br>  In Bezug auf Ausnahmen unterscheidet sich der Kotlin-Compiler darin, dass: <br><br>  1. Unterscheidet nicht zwischen aktivierten und nicht aktivierten Ausnahmen.  Alle Ausnahmen sind nur deaktiviert, und Sie entscheiden selbst, ob Sie sie abfangen und verarbeiten möchten. <br><br>  2. Try kann als Ausdruck verwendet werden. Sie können den try-Block ausführen und entweder die letzte Zeile daraus oder die letzte Zeile aus dem catch-Block zurückgeben. <br><br><pre> <code class="plaintext hljs">val value = try {Integer.parseInt(“lol”)} catch(e: NumberFormanException) { 4 } // </code> </pre><br>  3. Sie können auch eine ähnliche Konstruktion verwenden, wenn Sie auf ein Objekt verweisen, das möglicherweise nullwertfähig ist: <br><br><pre> <code class="plaintext hljs">val s = obj.money ?: throw IllegalArgumentException(“ , ”)</code> </pre><br><h4>  Java-Kompatibilität </h4><br>  Kotlin-Code kann in Java verwendet werden und umgekehrt.  Wie gehe ich mit Ausnahmen um? <br><br><ul><li>  Geprüfte Ausnahmen von Java in Kotlin können weder geprüft noch deklariert werden (da es in Kotlin keine geprüften Ausnahmen gibt). </li><li>  Mögliche geprüfte Ausnahmen von Kotlin (z. B. solche, die ursprünglich aus Java stammten) müssen in Java nicht geprüft werden. </li><li>  Wenn eine Überprüfung erforderlich ist, kann die Ausnahme mithilfe der Annotation @Throws in der Methode überprüft werden (es muss angegeben werden, welche Ausnahmen diese Methode auslösen kann).  Die obige Anmerkung dient nur der Java-Kompatibilität.  In der Praxis erklären viele Leute damit, dass eine solche Methode im Prinzip eine Ausnahme auslösen kann. </li></ul><br><h4>  Alternative zum Try-Catch-Block </h4><br>  Der Try-Catch-Block hat einen erheblichen Nachteil.  Wenn es angezeigt wird, wird ein Teil der Geschäftslogik innerhalb des Catch übertragen, und dies kann in einer der vielen oben genannten Methoden geschehen.  Wenn die Geschäftslogik über Blöcke oder die gesamte Anrufkette verteilt ist, ist es schwieriger zu verstehen, wie die Anwendung funktioniert.  Und die Lesbarkeitsblöcke selbst fügen keinen Code hinzu. <br><br><pre> <code class="plaintext hljs">try { HttpService.SendNotification(endpointUrl); MarkNotificationAsSent(); } catch (e: UnableToConnectToServerException) { MarkNotificationAsNotSent(); }</code> </pre><br>  Was sind die Alternativen? <br><br>  Eine Option bietet uns einen funktionalen Ansatz für die Ausnahmebehandlung.  Eine ähnliche Implementierung sieht folgendermaßen aus: <br><br><pre> <code class="plaintext hljs">val result: Try&lt;Result&gt; = Try{HttpService.SendNotification(endpointUrl)} when(result) { is Success -&gt; MarkNotificationAsSent() is Failure -&gt; MarkNotificationAsNotSent() }</code> </pre><br>  Wir haben die Möglichkeit, die Try-Monade zu verwenden.  Im Wesentlichen ist dies ein Container, der einen bestimmten Wert speichert.  flatMap ist eine Methode zum Arbeiten mit diesem Container, die zusammen mit dem aktuellen Wert eine Funktion übernehmen und erneut eine Monade zurückgeben kann. <br><br>  In diesem Fall wird der Anruf in die Try-Monade eingeschlossen (wir geben Try zurück).  Es kann an einem einzigen Ort verarbeitet werden - wo wir es brauchen.  Wenn die Ausgabe einen Wert hat, führen wir die folgenden Aktionen damit aus. Wenn eine Ausnahme ausgelöst wird, verarbeiten wir sie ganz am Ende der Kette. <br><br><h4>  Funktionale Ausnahmebehandlung </h4><br>  Wo kann ich Try bekommen? <br><br>  Erstens gibt es einige Community-Implementierungen der Klassen Try und Both.  Sie können sie nehmen oder sogar selbst eine Implementierung schreiben.  In einem der „Kampf“ -Projekte haben wir die selbst erstellte Try-Implementierung verwendet - wir haben es mit einer Klasse geschafft und hervorragende Arbeit geleistet. <br>  Zweitens gibt es die Arrow-Bibliothek, die Kotlin im Prinzip viele Funktionen hinzufügt.  Natürlich gibt es Try and Both. <br><br>  Außerdem erschien die Ergebnisklasse in Kotlin 1.3, auf die ich später noch näher eingehen werde. <br><br><h4>  Versuchen Sie es mit der Pfeilbibliothek als Beispiel </h4><br>  Die Pfeilbibliothek gibt uns eine Try-Klasse.  In der Tat kann es in zwei Zuständen sein: Erfolg oder Misserfolg: <br><br><ul><li>  Erfolg bei erfolgreichem Rückzug behält unseren Wert, </li><li>  Fehler speichert eine Ausnahme, die während der Ausführung eines Codeblocks aufgetreten ist. </li></ul><br>  Der Anruf ist wie folgt.  Natürlich ist es in einem regulären Try-Catch verpackt, aber dies wird irgendwo in unserem Code passieren. <br><br><pre> <code class="plaintext hljs">sealed class Try&lt;out A&gt; { data class Success&lt;out A&gt;(val value: A) : Try&lt;A&gt;() data class Failure(val e: Throwable) : Try&lt;Nothing&gt;() companion object { operator fun &lt;A&gt; invoke(body: () -&gt; A): Try&lt;A&gt; { return try { Success(body()) } catch (e: Exception) { Failure(e) } } }</code> </pre><br>  Dieselbe Klasse sollte die flatMap-Methode implementieren, mit der Sie eine Funktion übergeben und unsere try-Monade zurückgeben können: <br><br><pre> <code class="plaintext hljs">inline fun &lt;B&gt; map(f: (A) -&gt; B): Try&lt;B&gt; = flatMap { Success(f(it)) } inline fun &lt;B&gt; flatMap(f: (A) -&gt; TryOf&lt;B&gt;): Try&lt;B&gt; = when (this) { is Failure -&gt; this is Success -&gt; f(value) }</code> </pre><br>  Wofür ist das?  Um Fehler nicht für jedes der Ergebnisse zu verarbeiten, wenn wir mehrere davon haben.  Zum Beispiel haben wir mehrere Werte von verschiedenen Diensten erhalten und möchten diese kombinieren.  Tatsächlich können wir zwei Situationen haben: Entweder haben wir sie erfolgreich erhalten und kombiniert, oder es ist etwas gefallen.  Daher können wir Folgendes tun: <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Success(value=15)</code> </pre><br>  Wenn beide Aufrufe erfolgreich waren und wir die Werte erhalten haben, führen wir die Funktion aus.  Wenn sie nicht erfolgreich sind, wird Failure mit einer Ausnahme zurückgegeben. <br><br>  So sieht es aus, wenn etwas herunterfällt: <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { throw RuntimeException(“Oh no!”) } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no!</code> </pre><br>  Wir haben dieselbe Funktion verwendet, aber die Ausgabe ist ein Fehler einer RuntimeException. <br><br>  In der Pfeilbibliothek können Sie auch Konstrukte verwenden, bei denen es sich tatsächlich um syntaktischen Zucker handelt, insbesondere um Bindungen.  Trotzdem kann es über eine serielle flatMap umgeschrieben werden, aber durch das Binden können Sie es lesbar machen. <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val result3: Try&lt;Int&gt; = Try { throw RuntimeException(“Oh no, again!”) } val sum = binding { val (one) = result1 val (two) = result2 val (three) = result3 one + two + three } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no, again!</code> </pre><br>  Da eines der Ergebnisse gesunken ist, erhalten wir einen Fehler in der Ausgabe. <br><br>  Eine ähnliche Monade kann für asynchrone Anrufe verwendet werden.  Hier sind beispielsweise zwei Funktionen, die asynchron ausgeführt werden.  Wir kombinieren ihre Ergebnisse auf die gleiche Weise, ohne ihren Status separat zu überprüfen: <br><br><pre> <code class="plaintext hljs">fun funA(): Try&lt;Int&gt; { return Try { 1 } } fun funB(): Try&lt;Int&gt; { Thread.sleep(3000L) return Try { 2 } } val a = GlobalScope.async { funA() } val b = GlobalScope.async { funB() } val sum = runBlocking { a.await().flatMap { one -&gt; b.await().map {two -&gt; one + two } } }</code> </pre><br>  Und hier ist ein Beispiel für einen „Kampf“.  Wir haben eine Anfrage an den Server, wir verarbeiten sie, holen den Text von ihm und versuchen, ihn unserer Klasse zuzuordnen, von der wir bereits Daten zurückgeben. <br><br><pre> <code class="plaintext hljs">fun makeRequest(request: Request): Try&lt;List&lt;ResponseData&gt;&gt; = Try { httpClient.newCall(request).execute() } .map { it.body() } .flatMap { Try { ObjectMapper().readValue(it, ParsedResponse::class.java) } } .map { it.data } fun main(args : Array&lt;String&gt;) { val response = makeRequest(RequestBody(args)) when(response) { is Try.Success -&gt; response.data.toString() is Try.Failure -&gt; response.exception.message } }</code> </pre><br>  Try-Catch würde diesen Block viel weniger lesbar machen.  In diesem Fall erhalten wir am Ausgang response.data, die wir je nach Ergebnis verarbeiten können. <br><br><h4>  Ergebnis von Kotlin 1.3 </h4><br>  Kotlin 1.3 führte die Ergebnisklasse ein.  In der Tat ist es etwas ähnliches wie Try, aber mit einer Reihe von Einschränkungen.  Es ist ursprünglich für verschiedene asynchrone Operationen vorgesehen. <br><br><pre> <code class="plaintext hljs">val result: Result&lt;VeryImportantData&gt; = Result.runCatching { makeRequest() } .mapCatching { parseResponse(it) } .mapCatching { prepareData(it) } result.fold{ { data -&gt; println(“We have $data”) }, exception -&gt; println(“There is no any data, but it's your exception $exception”) } )</code> </pre><br>  Wenn nicht falsch, ist diese Klasse derzeit experimentell.  Sprachentwickler können ihre Signatur und ihr Verhalten ändern oder ganz entfernen. Daher ist es derzeit verboten, sie als Rückgabewert von Methoden oder Variablen zu verwenden.  Es kann jedoch als lokale (private) Variable verwendet werden.  Das heißt,  Tatsächlich kann es als Versuch aus dem Beispiel verwendet werden. <br><br><h3>  Schlussfolgerungen </h3><br>  Schlussfolgerungen, die ich für mich selbst gezogen habe: <br><br><ul><li>  Die Behandlung von Funktionsfehlern in Kotlin ist einfach und bequem. </li><li>  niemand stört sich daran, sie durch Versuch im klassischen Stil zu verarbeiten (sowohl das als auch das hat das Recht auf Leben; sowohl das als auch das sind bequem); </li><li>  Das Fehlen geprüfter Ausnahmen bedeutet nicht, dass Fehler nicht behandelt werden können. </li><li>  Ungefangene Ausnahmen bei der Produktion führen zu traurigen Konsequenzen. </li></ul><br>  Artikelautor: Alexey Shafranov, Leiter der Arbeitsgruppe (Java), Maxilect <br><br>  PS Wir veröffentlichen unsere Artikel auf mehreren Websites der Runet.  Abonnieren Sie unsere Seiten auf <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">VK</a> , <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">FB</a> oder <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=de&amp;u=">Telegramm-Kanal</a> , um mehr über unsere Veröffentlichungen und andere Maxilect-Nachrichten zu erfahren. </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/de447380/">https://habr.com/ru/post/de447380/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../de447368/index.html">Nicht nur Flöhe fangen. Warum Geschwindigkeit für jedes Geschäft so wichtig ist</a></li>
<li><a href="../de447370/index.html">Warum aufgrund eines kaputten Patentsystems immer noch der Schatten von Theranos über uns auftaucht</a></li>
<li><a href="../de447372/index.html">IT-Transformation ist unvermeidlich: Wo soll ich anfangen?</a></li>
<li><a href="../de447374/index.html">Programmgesteuertes Erstellen von Schnittstellenelementen mit PureLayout (Teil 2)</a></li>
<li><a href="../de447376/index.html">SNA Hackathon 2019</a></li>
<li><a href="../de447382/index.html">Das Buch "Einheit und C #. Gamedev von der Idee bis zur Umsetzung. 2nd ed</a></li>
<li><a href="../de447384/index.html">Leistungshalbleiter auf der Hut vor der Ökologie</a></li>
<li><a href="../de447388/index.html">TL; DR-Digest der ITMO University: nicht-klassische Zulassung zur Universität, bevorstehende Veranstaltungen und die interessantesten Materialien</a></li>
<li><a href="../de447390/index.html">AccelStor AFA-Konfigurationsrichtlinien für VMware vSphere</a></li>
<li><a href="../de447392/index.html">Drei Probleme von Diensten zur Überprüfung der englischen Grammatik und ob sie gelöst werden können</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>