<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>🏾 👩🏿‍🚀 👂🏾 Pengecualian Kotlin dan fitur-fiturnya 👬 🎂 🌒</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Perusahaan kami telah menggunakan Kotlin dalam produksi selama lebih dari dua tahun. Secara pribadi, saya menemukan bahasa ini sekitar setahun yang la...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Pengecualian Kotlin dan fitur-fiturnya</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/maxilect/blog/447380/">  Perusahaan kami telah menggunakan Kotlin dalam produksi selama lebih dari dua tahun.  Secara pribadi, saya menemukan bahasa ini sekitar setahun yang lalu.  Ada banyak topik untuk dibicarakan, tetapi hari ini kita akan berbicara tentang penanganan kesalahan, termasuk dalam gaya fungsional.  Saya akan memberitahu Anda bagaimana melakukan ini di Kotlin. <br><br><img src="https://habrastorage.org/webt/mb/bh/cp/mbbhcprsketr78wg8twpwhijg0y.jpeg" alt="gambar"><br><br>  <i>(Foto dari pertemuan tentang topik ini, yang terjadi di kantor salah satu perusahaan Taganrog. Alexey Shafranov, pemimpin kelompok kerja (Jawa) di Maxilekt, berbicara)</i> <br><a name="habracut"></a><br><h3>  Bagaimana Anda bisa menangani kesalahan pada prinsipnya? </h3><br>  Saya menemukan beberapa cara: <br><br><ul><li>  Anda dapat menggunakan beberapa <b>nilai balik</b> sebagai penunjuk ke fakta bahwa ada kesalahan; </li><li>  Anda dapat menggunakan <b>parameter indikator</b> untuk tujuan yang sama, </li><li>  masukkan <b>variabel global</b> </li><li>  menangani <b>pengecualian</b> </li><li>  Tambahkan <b>Kontrak (DbC)</b> . </li></ul><br>  Mari kita membahas lebih rinci tentang masing-masing opsi. <br><br><h4>  Nilai pengembalian </h4><br>  Nilai "ajaib" tertentu dikembalikan jika terjadi kesalahan.  Jika Anda pernah menggunakan bahasa skrip, Anda harus melihat konstruksi yang serupa. <br><br>  Contoh 1: <br><br><pre><code class="plaintext hljs">function sqrt(x) { if(x &lt; 0) return -1; else return √x; }</code> </pre> <br>  Contoh 2: <br><br><pre> <code class="plaintext hljs">function getUser(id) { result = db.getUserById(id) if (result) return result as User else return “Can't find user ” + id }</code> </pre><br><h4>  Parameter indikator </h4><br>  Parameter tertentu yang diteruskan ke fungsi digunakan.  Setelah mengembalikan nilai dengan parameter, Anda dapat melihat apakah ada kesalahan di dalam fungsi. <br><br>  Contoh: <br><br><pre> <code class="plaintext hljs">function divide(x,y,out Success) { if (y == 0) Success = false else Success = true return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4>  Variabel global </h4><br>  Variabel global bekerja dengan cara yang kira-kira sama. <br><br>  Contoh: <br><br><pre> <code class="plaintext hljs">global Success = true function divide(x,y) { if (y == 0) Success = false else return x/y } divide(10, 11, Success) id (!Success) //handle error</code> </pre><br><h4>  Pengecualian </h4><br>  Kita semua terbiasa dengan pengecualian.  Mereka digunakan hampir di mana-mana. <br><br>  Contoh: <br><br><pre> <code class="plaintext hljs">function divide(x,y) { if (y == 0) throw Exception() else return x/y } try{ divide(10, 0)} catch (e) {//handle exception}</code> </pre><br><h4>  Kontrak (DbC) </h4><br>  Terus terang, saya belum pernah melihat pendekatan ini secara langsung.  Dengan googling lama, saya menemukan bahwa Kotlin 1.3 memiliki perpustakaan yang benar-benar memungkinkan penggunaan kontrak.  Yaitu  Anda dapat mengatur kondisi pada variabel yang diteruskan ke fungsi, kondisi pada nilai balik, jumlah panggilan, dari mana panggilan itu berasal, dll.  Dan jika semua kondisi terpenuhi, diyakini bahwa fungsi tersebut bekerja dengan benar. <br><br>  Contoh: <br><br><pre> <code class="plaintext hljs">function sqrt (x) pre-condition (x &gt;= 0) post-condition (return &gt;= 0) begin calculate sqrt from x end</code> </pre><br>  Jujur, perpustakaan ini memiliki sintaks yang mengerikan.  Mungkin itu sebabnya saya belum melihat hal seperti itu secara langsung. <br><br><h3>  Pengecualian di Jawa </h3><br>  Mari kita beralih ke Jawa dan bagaimana semuanya bekerja dari awal. <br><br><img src="https://habrastorage.org/webt/gk/oo/mw/gkoomw72k7yp5mhpi9ebpt02g-i.png" alt="gambar"><br><br>  Saat mendesain bahasa, ada dua jenis pengecualian: <br><br><ul><li>  diperiksa - diperiksa; </li><li>  tidak dicentang - tidak dicentang. </li></ul><br>  Untuk apa pengecualian diperiksa?  Secara teoritis, mereka diperlukan sehingga orang harus memeriksa kesalahan.  Yaitu  jika pengecualian yang diperiksa tertentu dimungkinkan, maka harus diperiksa nanti.  Secara teoritis, pendekatan ini seharusnya mengarah pada tidak adanya kesalahan yang tidak diproses dan kualitas kode yang ditingkatkan.  Tetapi dalam praktiknya tidak demikian.  Saya pikir semua orang setidaknya satu kali dalam hidup mereka melihat blok penangkap kosong. <br><br>  Mengapa ini bisa buruk? <br><br>  Ini adalah contoh klasik langsung dari dokumentasi Kotlin - antarmuka dari JDK yang diimplementasikan dalam StringBuilder: <br><br><pre> <code class="plaintext hljs">Appendable append(CharSequence csq) throws IOException; try { log.append(message) } catch (IOException e) { //Must be safe }</code> </pre><br>  Saya yakin Anda telah menemukan cukup banyak kode yang dibungkus dengan try-catch, di mana catch adalah blok kosong, karena situasi seperti itu seharusnya tidak terjadi, menurut pengembang.  Dalam banyak kasus, penanganan pengecualian yang diperiksa dilaksanakan dengan cara berikut: mereka hanya membuang RuntimeException dan menangkapnya di suatu tempat di atas (atau tidak menangkapnya ...). <br><br><pre> <code class="plaintext hljs">try { // do something } catch (IOException e) { throw new RuntimeException(e); //  - ...</code> </pre><br><h3>  Apa yang mungkin terjadi di Kotlin </h3><br>  Dalam hal pengecualian, kompiler Kotlin berbeda dalam hal: <br><br>  1. Tidak membedakan antara pengecualian yang diperiksa dan yang tidak dicentang.  Semua pengecualian hanya tidak dicentang, dan Anda memutuskan sendiri apakah akan menangkap dan memprosesnya. <br><br>  2. Coba dapat digunakan sebagai ekspresi - Anda dapat menjalankan blok try dan mengembalikan baris terakhir dari itu, atau mengembalikan baris terakhir dari catch catch. <br><br><pre> <code class="plaintext hljs">val value = try {Integer.parseInt(“lol”)} catch(e: NumberFormanException) { 4 } // </code> </pre><br>  3. Anda juga dapat menggunakan konstruksi serupa ketika merujuk ke beberapa objek, yang mungkin dapat dibatalkan: <br><br><pre> <code class="plaintext hljs">val s = obj.money ?: throw IllegalArgumentException(“ , ”)</code> </pre><br><h4>  Kompatibilitas Java </h4><br>  Kode Kotlin dapat digunakan di Jawa dan sebaliknya.  Bagaimana cara menangani pengecualian? <br><br><ul><li>  Pengecualian yang diperiksa dari Jawa di Kotlin tidak dapat dicek atau dinyatakan (karena tidak ada pengecualian yang dicek di Kotlin). </li><li>  Kemungkinan pengecualian yang diperiksa dari Kotlin (misalnya, yang berasal dari Jawa) tidak perlu diperiksa di Jawa. </li><li>  Jika perlu untuk memeriksa, pengecualian dapat dibuat diverifikasi menggunakan penjelasan @Throws dalam metode (perlu untuk menunjukkan pengecualian yang dapat dilemparkan metode ini).  Anotasi di atas hanya untuk kompatibilitas Java.  Namun dalam praktiknya, banyak orang menggunakannya untuk menyatakan bahwa metode semacam itu, pada prinsipnya, dapat menimbulkan semacam pengecualian. </li></ul><br><h4>  Alternatif untuk coba-tangkap blok </h4><br>  Blok try-catch memiliki kelemahan signifikan.  Ketika itu muncul, bagian dari logika bisnis ditransfer ke dalam tangkapan, dan ini bisa terjadi di salah satu dari banyak metode di atas.  Saat logika bisnis tersebar di blok atau seluruh rantai panggilan, akan lebih sulit untuk memahami cara kerja aplikasi.  Dan blok keterbacaan sendiri tidak menambahkan kode. <br><br><pre> <code class="plaintext hljs">try { HttpService.SendNotification(endpointUrl); MarkNotificationAsSent(); } catch (e: UnableToConnectToServerException) { MarkNotificationAsNotSent(); }</code> </pre><br>  Apa alternatifnya? <br><br>  Satu opsi menawarkan kita pendekatan fungsional untuk penanganan pengecualian.  Implementasi serupa terlihat seperti ini: <br><br><pre> <code class="plaintext hljs">val result: Try&lt;Result&gt; = Try{HttpService.SendNotification(endpointUrl)} when(result) { is Success -&gt; MarkNotificationAsSent() is Failure -&gt; MarkNotificationAsNotSent() }</code> </pre><br>  Kami memiliki kesempatan untuk menggunakan Try monad.  Intinya, ini adalah wadah yang menyimpan beberapa nilai.  flatMap adalah metode bekerja dengan wadah ini, yang, bersama dengan nilai saat ini, dapat mengambil fungsi dan, sekali lagi, mengembalikan monad. <br><br>  Dalam hal ini, panggilan dibungkus dengan Try monad (kami mengembalikan Try).  Itu dapat diproses di satu tempat - di mana kita membutuhkannya.  Jika output memiliki nilai, kami melakukan tindakan berikut dengan itu, jika pengecualian dilemparkan, kami memprosesnya di akhir rantai. <br><br><h4>  Penanganan Pengecualian Fungsional </h4><br>  Di mana saya bisa mencoba? <br><br>  Pertama, ada beberapa implementasi komunitas dari kelas Try and Either.  Anda dapat mengambilnya atau bahkan menulis implementasi sendiri.  Dalam salah satu proyek "pertempuran", kami menggunakan implementasi Try yang dibuat sendiri - kami berhasil dengan satu kelas dan melakukan pekerjaan yang sangat baik. <br>  Kedua, ada perpustakaan Arrow, yang pada prinsipnya menambahkan banyak fungsi ke Kotlin.  Secara alami, ada Try and Either. <br><br>  Selain itu, kelas Hasil muncul di Kotlin 1.3, yang akan saya bahas lebih rinci nanti. <br><br><h4>  Coba gunakan perpustakaan Arrow sebagai contoh </h4><br>  Perpustakaan Arrow memberi kita kelas Try.  Bahkan, itu bisa di dua negara: Sukses atau Gagal: <br><br><ul><li>  Keberhasilan penarikan yang berhasil akan mempertahankan nilai kami, </li><li>  Kegagalan menyimpan pengecualian yang terjadi selama eksekusi blok kode. </li></ul><br>  Panggilannya adalah sebagai berikut.  Secara alami, ini dibungkus dengan try-catch reguler, tetapi ini akan terjadi di suatu tempat di dalam kode kita. <br><br><pre> <code class="plaintext hljs">sealed class Try&lt;out A&gt; { data class Success&lt;out A&gt;(val value: A) : Try&lt;A&gt;() data class Failure(val e: Throwable) : Try&lt;Nothing&gt;() companion object { operator fun &lt;A&gt; invoke(body: () -&gt; A): Try&lt;A&gt; { return try { Success(body()) } catch (e: Exception) { Failure(e) } } }</code> </pre><br>  Kelas yang sama harus menerapkan metode flatMap, yang memungkinkan Anda untuk melewati suatu fungsi dan mengembalikan try monad kami: <br><br><pre> <code class="plaintext hljs">inline fun &lt;B&gt; map(f: (A) -&gt; B): Try&lt;B&gt; = flatMap { Success(f(it)) } inline fun &lt;B&gt; flatMap(f: (A) -&gt; TryOf&lt;B&gt;): Try&lt;B&gt; = when (this) { is Failure -&gt; this is Success -&gt; f(value) }</code> </pre><br>  Untuk apa ini?  Agar tidak memproses kesalahan untuk setiap hasil ketika kami memiliki beberapa dari mereka.  Misalnya, kami mendapat beberapa nilai dari berbagai layanan dan ingin menggabungkannya.  Sebenarnya, kita dapat memiliki dua situasi: apakah kita berhasil menerima dan menggabungkannya, atau sesuatu jatuh.  Karena itu, kita dapat melakukan hal berikut: <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Success(value=15)</code> </pre><br>  Jika kedua panggilan berhasil dan kami mendapat nilai, kami menjalankan fungsinya.  Jika mereka tidak berhasil, Kegagalan akan kembali dengan pengecualian. <br><br>  Inilah yang terlihat jika sesuatu jatuh: <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { throw RuntimeException(“Oh no!”) } val sum = result1.flatMap { one -&gt; result2.map { two -&gt; one + two } } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no!</code> </pre><br>  Kami menggunakan fungsi yang sama, tetapi hasilnya adalah Kegagalan dari RuntimeException. <br><br>  Juga, perpustakaan Arrow memungkinkan Anda untuk menggunakan konstruksi yang sebenarnya gula sintaksis, khususnya yang mengikat.  Semua hal yang sama dapat ditulis ulang melalui flatMap serial, tetapi mengikat memungkinkan Anda untuk membuatnya dapat dibaca. <br><br><pre> <code class="plaintext hljs">val result1: Try&lt;Int&gt; = Try { 11 } val result2: Try&lt;Int&gt; = Try { 4 } val result3: Try&lt;Int&gt; = Try { throw RuntimeException(“Oh no, again!”) } val sum = binding { val (one) = result1 val (two) = result2 val (three) = result3 one + two + three } println(sum) //Failure(exception=java.lang.RuntimeException: Oh no, again!</code> </pre><br>  Mengingat bahwa salah satu hasil telah jatuh, kami mendapatkan kesalahan pada output. <br><br>  Monad serupa dapat digunakan untuk panggilan tidak sinkron.  Misalnya, berikut adalah dua fungsi yang berjalan secara tidak sinkron.  Kami menggabungkan hasil mereka dengan cara yang sama, tanpa secara terpisah memeriksa status mereka: <br><br><pre> <code class="plaintext hljs">fun funA(): Try&lt;Int&gt; { return Try { 1 } } fun funB(): Try&lt;Int&gt; { Thread.sleep(3000L) return Try { 2 } } val a = GlobalScope.async { funA() } val b = GlobalScope.async { funB() } val sum = runBlocking { a.await().flatMap { one -&gt; b.await().map {two -&gt; one + two } } }</code> </pre><br>  Dan ini adalah contoh "pertarungan" yang lebih banyak.  Kami memiliki permintaan ke server, kami memprosesnya, mendapatkan tubuh dari itu dan mencoba memetakannya ke kelas kami, dari mana kami sudah mengembalikan data. <br><br><pre> <code class="plaintext hljs">fun makeRequest(request: Request): Try&lt;List&lt;ResponseData&gt;&gt; = Try { httpClient.newCall(request).execute() } .map { it.body() } .flatMap { Try { ObjectMapper().readValue(it, ParsedResponse::class.java) } } .map { it.data } fun main(args : Array&lt;String&gt;) { val response = makeRequest(RequestBody(args)) when(response) { is Try.Success -&gt; response.data.toString() is Try.Failure -&gt; response.exception.message } }</code> </pre><br>  Coba-tangkap akan membuat blok ini jauh lebih mudah dibaca.  Dan dalam hal ini, kita mendapatkan response.data pada output, yang dapat kita proses tergantung pada hasilnya. <br><br><h4>  Hasil dari Kotlin 1.3 </h4><br>  Kotlin 1.3 memperkenalkan kelas Hasil.  Bahkan, itu mirip dengan Coba, tetapi dengan sejumlah keterbatasan.  Ini awalnya dimaksudkan untuk digunakan untuk berbagai operasi asinkron. <br><br><pre> <code class="plaintext hljs">val result: Result&lt;VeryImportantData&gt; = Result.runCatching { makeRequest() } .mapCatching { parseResponse(it) } .mapCatching { prepareData(it) } result.fold{ { data -&gt; println(“We have $data”) }, exception -&gt; println(“There is no any data, but it's your exception $exception”) } )</code> </pre><br>  Jika tidak salah, kelas ini sedang dalam tahap percobaan.  Pengembang bahasa dapat mengubah tanda tangannya, perilaku, atau menghapusnya sama sekali, sehingga saat ini dilarang untuk menggunakannya sebagai nilai balik dari metode atau variabel.  Namun, ini dapat digunakan sebagai variabel lokal (pribadi).  Yaitu  pada kenyataannya, ini dapat digunakan sebagai percobaan dari contoh. <br><br><h3>  Kesimpulan </h3><br>  Kesimpulan yang saya buat untuk diri saya sendiri: <br><br><ul><li>  penanganan kesalahan fungsional di Kotlin sederhana dan nyaman; </li><li>  tidak ada yang mengganggu untuk memprosesnya melalui try-catch dalam gaya klasik (keduanya itu dan yang memiliki hak untuk hidup; keduanya itu dan yang nyaman); </li><li>  tidak adanya pengecualian yang diperiksa tidak berarti bahwa kesalahan tidak dapat ditangani; </li><li>  pengecualian produksi yang tanpa tertangkap menyebabkan konsekuensi yang menyedihkan. </li></ul><br>  Penulis artikel: Alexey Shafranov, pemimpin kelompok kerja (Jawa), Maxilect <br><br>  PS Kami menerbitkan artikel kami di beberapa situs Runet.  Berlangganan ke halaman kami di <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u=">VK</a> , <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u=">FB</a> atau <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=id&amp;u=">saluran Telegram</a> untuk mencari tahu tentang semua publikasi kami dan berita Maxilect lainnya. </div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/id447380/">https://habr.com/ru/post/id447380/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../id447368/index.html">Bukan hanya menangkap kutu. Mengapa kecepatan sangat penting untuk setiap toko</a></li>
<li><a href="../id447370/index.html">Mengapa, karena sistem paten yang rusak, bayangan Theranos masih membayangi kita</a></li>
<li><a href="../id447372/index.html">Transformasi TI tidak bisa dihindari: harus mulai dari mana</a></li>
<li><a href="../id447374/index.html">Membuat Elemen Antarmuka Secara Programatis Menggunakan PureLayout (Bagian 2)</a></li>
<li><a href="../id447376/index.html">SNA Hackathon 2019</a></li>
<li><a href="../id447382/index.html">Buku "Persatuan dan C #. Gamedev dari ide hingga implementasi. 2nd ed</a></li>
<li><a href="../id447384/index.html">Semikonduktor daya jaga ekologi</a></li>
<li><a href="../id447388/index.html">TL; DR-digest dari ITMO University: penerimaan non-klasik ke universitas, acara mendatang dan materi yang paling menarik</a></li>
<li><a href="../id447390/index.html">Pedoman konfigurasi AFA AccelStor untuk VMware vSphere</a></li>
<li><a href="../id447392/index.html">Tiga masalah layanan untuk memeriksa tata bahasa Inggris, dan apakah itu bisa diselesaikan</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>