<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>üå≤ üë©üèΩ‚Äç‚úàÔ∏è üåØ Situa√ß√µes excepcionais: parte 1 de 4 ü•î üéôÔ∏è üê∂</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="1. Introdu√ß√£o 


 √â hora de falar sobre exce√ß√µes ou, melhor dizendo, sobre situa√ß√µes excepcionais. Antes de come√ßarmos, vejamos a defini√ß√£o. O que √© u...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Situa√ß√µes excepcionais: parte 1 de 4</h1><div class="post__body post__body_full"><div class="post__text post__text-html" id="post-content-body" data-io-article-url="https://habr.com/ru/company/clrium/blog/454630/"><p> <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=pt&amp;u="><img width="350" align="left" src="https://habrastorage.org/webt/vh/7j/tq/vh7jtqhzbne4h3rjhprca2pruhu.png"></a> </p><br><h2 id="introduction">  1. Introdu√ß√£o </h2><br><p>  √â hora de falar sobre exce√ß√µes ou, melhor dizendo, sobre situa√ß√µes excepcionais.  Antes de come√ßarmos, vejamos a defini√ß√£o.  O que √© uma situa√ß√£o excepcional? </p><br><p>  Essa √© uma situa√ß√£o que torna incorreta a execu√ß√£o do c√≥digo atual ou subsequente.  Quero dizer diferente de como foi projetado ou planejado.  Tal situa√ß√£o compromete a integridade de um aplicativo ou de sua parte, por exemplo, um objeto.  Ele traz o aplicativo para um estado extraordin√°rio ou excepcional. </p><br><p>  Mas por que precisamos definir essa terminologia?  Porque isso nos manter√° em alguns limites.  Se n√£o seguirmos a terminologia, podemos nos afastar muito de um conceito projetado que pode resultar em muitas situa√ß√µes amb√≠guas.  Vamos ver alguns exemplos pr√°ticos: <br><br></p><br><pre><code class="plaintext hljs">struct Number { public static Number Parse(string source) { // ... if(!parsed) { throw new ParsingException(); } // ... } public static bool TryParse(string source, out Number result) { // .. return parsed; } }</code> </pre> <br><p>  Este exemplo parece um pouco estranho, e √© por uma raz√£o.  Eu criei esse c√≥digo um pouco artificial para mostrar a import√¢ncia dos problemas que aparecem nele.  Primeiro, vejamos o m√©todo <code>Parse</code> .  Por que isso deveria lan√ßar uma exce√ß√£o? </p><a name="habracut"></a><br><ul><li>  Como o par√¢metro aceito √© uma sequ√™ncia, mas sua sa√≠da √© um n√∫mero, que √© um tipo de valor.  Este n√∫mero n√£o pode indicar a validade dos c√°lculos: apenas existe.  Em outras palavras, o m√©todo n√£o possui meios em sua interface para comunicar um problema em potencial. </li><li>  Por outro lado, o m√©todo espera uma sequ√™ncia correta que contenha algum n√∫mero e nenhum caractere redundante.  Se n√£o contiver, h√° um problema nos pr√©-requisitos do m√©todo: o c√≥digo que chama nosso m√©todo passou dados incorretos. </li></ul><br><p>  Portanto, a situa√ß√£o em que esse m√©todo obt√©m uma string com dados incorretos √© excepcional, pois o m√©todo n√£o pode retornar um valor correto nem nada.  Assim, a √∫nica maneira √© lan√ßar uma exce√ß√£o. </p><br><p>  A segunda variante do m√©todo pode sinalizar alguns problemas com os dados de entrada: o valor de retorno aqui √© <code>boolean</code> que indica uma execu√ß√£o bem-sucedida do m√©todo.  Este m√©todo n√£o precisa usar exce√ß√µes para sinalizar problemas: todos eles s√£o cobertos pelo valor de retorno <code>false</code> . </p><br><h2 id="overview">  Vis√£o geral </h2><br><p>  O tratamento de exce√ß√µes pode parecer t√£o f√°cil quanto o ABC: precisamos apenas colocar blocos <code>try-catch</code> e aguardar os eventos correspondentes.  No entanto, essa simplicidade se tornou poss√≠vel devido ao tremendo trabalho das equipes de CLR e CoreCLR que unificaram todos os erros provenientes de todas as dire√ß√µes e fontes no CLR.  Para entender sobre o que falaremos a seguir, vejamos um diagrama: </p><br><p><img src="https://habrastorage.org/getpro/habr/post_images/e12/163/521/e121635214ad6b5b5675ba4231eb85e7.png"></p><br><p>  Podemos ver que dentro do grande .NET Framework existem dois mundos: tudo o que pertence ao CLR e tudo o que n√£o pertence, incluindo todos os erros poss√≠veis que aparecem no Windows e em outras partes do mundo inseguro. </p><br><ul><li>  O SEH (Structured Exception Handling) √© uma maneira padr√£o pelo qual o Windows lida com exce√ß√µes.  Quando m√©todos <code>unsafe</code> s√£o chamados e exce√ß√µes s√£o lan√ßadas, ocorre a convers√£o insegura de exce√ß√µes &lt;-&gt; CLR nas duas dire√ß√µes: de inseguras para CLR e para tr√°s.  Isso ocorre porque o CLR pode chamar um m√©todo n√£o seguro, que pode chamar um m√©todo CLR por sua vez. </li><li>  O Vectored Exception Handling (VEH) √© uma raiz do SEH e permite que voc√™ coloque seus manipuladores em locais onde exce√ß√µes possam ser lan√ßadas.  Em particular, √© usado para colocar <code>FirstChanceException</code> . </li><li>  As exce√ß√µes do COM + aparecem quando a fonte de um problema √© um componente do COM.  Nesse caso, uma camada entre COM e um m√©todo .NET deve converter um erro COM em uma exce√ß√£o .NET. </li><li>  E, √© claro, inv√≥lucros para HRESULT.  Eles s√£o introduzidos para converter um modelo WinAPI (um c√≥digo de erro est√° contido em um valor de retorno, enquanto os valores de retorno s√£o obtidos usando par√¢metros de m√©todo) em um modelo de exce√ß√µes, porque √© uma exce√ß√£o padr√£o do .NET. </li></ul><br><p>  Por outro lado, existem idiomas acima da CLI, cada um dos quais mais ou menos possui fun√ß√µes para lidar com exce√ß√µes.  Por exemplo, recentemente o VB.NET ou o F # tiveram uma funcionalidade de manipula√ß√£o de exce√ß√µes mais rica, expressa em v√°rios filtros que n√£o existiam no C #. </p><br><h2 id="return-codes-vs-exception">  C√≥digos de retorno vs.  exce√ß√£o </h2><br><p>  Separadamente, devo mencionar um modelo de tratamento de erros de aplicativo usando c√≥digos de retorno.  A id√©ia de simplesmente retornar um erro √© clara e clara.  Al√©m disso, se tratarmos as exce√ß√µes como um operador <code>goto</code> , o uso de c√≥digos de retorno se tornar√° mais razo√°vel: nesse caso, o usu√°rio de um m√©todo v√™ a possibilidade de erros e pode entender quais erros podem ocorrer.  No entanto, n√£o vamos adivinhar o que √© melhor e para qu√™, mas discuta o problema da escolha usando uma teoria bem fundamentada. </p><br><p>  Vamos supor que todos os m√©todos tenham interfaces para lidar com erros.  Todos os m√©todos se pareceriam com: </p><br><pre> <code class="plaintext hljs">public bool TryParseInteger(string source, out int result); public DialogBoxResult OpenDialogBox(...); public WebServiceResult IWebService.GetClientsList(...); public class DialogBoxResult : ResultBase { ... } public class WebServiceResult : ResultBase { ... }</code> </pre> <br><p>  E seu uso seria semelhante a: </p><br><pre> <code class="plaintext hljs">public ShowClientsResult ShowClients(string group) { if(!TryParseInteger(group, out var clientsGroupId)) return new ShowClientsResult { Reason = ShowClientsResult.Reason.ParsingFailed }; var webResult = _service.GetClientsList(clientsGroupId); if(!webResult.Successful) { return new ShowClientsResult { Reason = ShowClientsResult.Reason.ServiceFailed, WebServiceResult = webResult }; } var dialogResult = _dialogsService.OpenDialogBox(webResult.Result); if(!dialogResult.Successful) { return new ShowClientsResult { Reason = ShowClientsResult.Reason.DialogOpeningFailed, DialogServiceResult = dialogResult }; } return ShowClientsResult.Success(); }</code> </pre> <br><p>  Voc√™ pode pensar que esse c√≥digo est√° sobrecarregado com o tratamento de erros.  No entanto, gostaria que voc√™ reconsiderasse sua posi√ß√£o: tudo aqui √© uma emula√ß√£o de um mecanismo que lan√ßa e manipula exce√ß√µes. </p><br><p>  Como um m√©todo pode relatar um problema?  Isso pode ser feito usando uma interface para relatar erros.  Por exemplo, no m√©todo <code>TryParseInteger</code> , essa interface √© representada por um valor de retorno: se tudo estiver OK, o m√©todo retornar√° <code>true</code> .  Se n√£o estiver bom, ele retornar√° <code>false</code> .  No entanto, h√° uma desvantagem aqui: o valor real √© retornado atrav√©s do par√¢metro <code>out int result</code> .  A desvantagem √© que, por um lado, o valor de retorno √© logicamente e, pela percep√ß√£o, tem mais ess√™ncia de "valor de retorno" do que <code>out</code> par√¢metro <code>out</code> . Por outro lado, nem sempre nos preocupamos com erros. Na verdade, se uma string destinada a a an√°lise vem de um servi√ßo que gerou essa sequ√™ncia, n√£o precisamos verificar se h√° erros: a sequ√™ncia sempre ser√° correta e adequada para a an√°lise. No entanto, suponha que adotemos outra implementa√ß√£o do m√©todo: </p><br><pre> <code class="plaintext hljs">public int ParseInt(string source);</code> </pre> <br><p>  Depois, h√° uma pergunta: se uma string tem erros, o que o m√©todo deve fazer?  Deve retornar zero?  Isso n√£o estar√° correto: n√£o h√° zero na string.  Nesse caso, temos um conflito de interesses: a primeira variante possui muito c√≥digo, enquanto a segunda variante n√£o tem como relatar erros.  No entanto, √© realmente f√°cil decidir quando usar c√≥digos de retorno e quando usar exce√ß√µes. </p><br><blockquote>  Se receber um erro for uma norma, escolha um c√≥digo de retorno.  Por exemplo, √© normal quando um algoritmo de an√°lise de texto encontra erros em um texto, mas se outro algoritmo que trabalha com uma sequ√™ncia analisada obtiver um erro de um analisador, ele poder√° ser cr√≠tico ou, em outras palavras, excepcional. </blockquote><br><h2 id="try-catch-finally-in-brief">  Tente pegar finalmente </h2><br><p>  Um bloco <code>try</code> cobre uma se√ß√£o em que um programador espera obter uma situa√ß√£o cr√≠tica que √© tratada como norma por c√≥digo externo.  Em outras palavras, se algum c√≥digo considerar seu estado interno inconsistente com base em algumas regras e gerar uma exce√ß√£o, um sistema externo, com uma vis√£o mais ampla da mesma situa√ß√£o, poder√° capturar essa exce√ß√£o usando um bloco <code>catch</code> e normalizar a execu√ß√£o do c√≥digo do aplicativo .  Assim, <em>voc√™ legaliza exce√ß√µes nesta se√ß√£o do c√≥digo, capturando-as</em> .  Penso que √© uma ideia importante que justifica a proibi√ß√£o de capturar todas as <code>try-catch(Exception ex){ ...}</code> <em>por precau√ß√£o</em> . </p><br><p>  Isso n√£o significa que capturar exce√ß√µes contradiz alguma ideologia.  Eu digo que voc√™ deve pegar apenas os erros que voc√™ espera de uma se√ß√£o espec√≠fica do c√≥digo.  Por exemplo, voc√™ n√£o pode esperar todos os tipos de exce√ß√µes herdadas de <code>ArgumentException</code> ou n√£o pode obter <code>NullReferenceException</code> , porque muitas vezes significa que um problema est√° mais no <em>seu</em> c√≥digo do que no chamado.  Mas √© apropriado esperar que voc√™ n√£o consiga abrir um arquivo pretendido.  Mesmo se voc√™ tiver 200% de certeza de que ser√° capaz, n√£o se esque√ßa de conferir. </p><br><p>  O bloco <code>finally</code> tamb√©m √© bem conhecido.  √â adequado para todos os casos cobertos por blocos <code>try-catch</code> .  Exceto por v√°rias situa√ß√µes <em>especiais</em> raras, esse bloco <em>sempre</em> funcionar√°.  Por que essa garantia de desempenho foi introduzida?  Limpar os recursos e grupos de objetos que foram alocados ou capturados no bloco <code>try</code> e pelos quais esse bloco √© respons√°vel. </p><br><p>  Esse bloco geralmente √© usado sem o bloco <code>catch</code> quando n√£o nos importamos com o erro que quebrou um algoritmo, mas precisamos limpar todos os recursos alocados para esse algoritmo.  Vejamos um exemplo simples: um algoritmo de c√≥pia de arquivo precisa de dois arquivos abertos e um intervalo de mem√≥ria para um buffer de caixa.  Imagine que alocamos mem√≥ria e abrimos um arquivo, mas n√£o conseguimos abrir outro.  Para agrupar tudo em uma "transa√ß√£o" atomicamente, colocamos todas as tr√™s opera√ß√µes em um √∫nico bloco de <code>try</code> (como uma variante de implementa√ß√£o) com os recursos <code>finally</code> limpos. Pode parecer um exemplo simplificado, mas o mais importante √© mostrar a ess√™ncia. </p><br><p>  O que C # realmente falta √© um bloco de <code>fault</code> que √© ativado sempre que ocorre um erro.  √â como <code>finally</code> usar ester√≥ides.  Se tiv√©ssemos isso, poder√≠amos, por exemplo, criar um √∫nico ponto de entrada para registrar situa√ß√µes excepcionais: </p><br><pre> <code class="plaintext hljs">try { //... } fault exception { _logger.Warn(exception); }</code> </pre><br><p>  Outra coisa que devo mencionar nesta introdu√ß√£o s√£o os filtros de exce√ß√£o.  N√£o √© um novo recurso na plataforma .NET, mas os desenvolvedores de C # podem ser novos: a filtragem de exce√ß√µes apareceu apenas na v.  6.0  Os filtros devem normalizar uma situa√ß√£o em que h√° um √∫nico tipo de exce√ß√£o que combina v√°rios tipos de erros.  Isso deve nos ajudar quando queremos lidar com um cen√°rio espec√≠fico, mas precisamos capturar todo o grupo de erros primeiro e filtr√°-los mais tarde.  Claro, quero dizer o c√≥digo do seguinte tipo: </p><br><pre> <code class="plaintext hljs">try { //... } catch (ParserException exception) { switch(exception.ErrorCode) { case ErrorCode.MissingModifier: // ... break; case ErrorCode.MissingBracket: // ... break; default: throw; } }</code> </pre> <br><p>  Bem, agora podemos reescrever esse c√≥digo corretamente: </p><br><pre> <code class="plaintext hljs">try { //... } catch (ParserException exception) when (exception.ErrorCode == ErrorCode.MissingModifier) { // ... } catch (ParserException exception) when (exception.ErrorCode == ErrorCode.MissingBracket) { // ... }</code> </pre> <br><p>  A melhoria aqui n√£o est√° na falta de constru√ß√£o de <code>switch</code> .  Eu acredito que essa nova constru√ß√£o √© melhor em v√°rias coisas: </p><br><ul><li>  usando <code>when</code> para filtrar, captamos exatamente o que queremos e √© certo em termos de ideologia; </li><li>  o c√≥digo se torna mais leg√≠vel neste novo formul√°rio.  Examinando o c√≥digo, nosso c√©rebro pode identificar blocos para lidar com erros com mais facilidade, pois inicialmente procura por <code>catch</code> e n√£o <code>switch-case</code> ; </li><li>  o √∫ltimo mas n√£o menos importante: uma compara√ß√£o preliminar √© ANTES de entrar no bloco catch.  Isso significa que, se fizermos suposi√ß√µes erradas sobre situa√ß√µes em potencial, essa constru√ß√£o funcionar√° mais r√°pido do que <code>switch</code> no caso de lan√ßar uma exce√ß√£o novamente. </li></ul><br><p>  Muitas fontes dizem que a caracter√≠stica peculiar desse c√≥digo √© que a filtragem ocorre <em>antes do</em> desenrolamento da pilha.  Voc√™ pode ver isso em situa√ß√µes em que n√£o h√° outras chamadas, exceto a habitual, entre o local em que uma exce√ß√£o √© lan√ßada e o local em que a verifica√ß√£o de filtragem ocorre. </p><br><pre> <code class="plaintext hljs">static void Main() { try { Foo(); } catch (Exception ex) when (Check(ex)) { ; } } static void Foo() { Boo(); } static void Boo() { throw new Exception("1"); } static bool Check(Exception ex) { return ex.Message == "1"; }</code> </pre> <br><p><img src="https://habrastorage.org/getpro/habr/post_images/e41/c44/c6b/e41c44c6b41164af3aff1aa9489f417f.png" alt="Empilhar sem desenrolar"></p><br><p>  Voc√™ pode ver na imagem que o rastreamento de pilha cont√©m n√£o apenas a primeira chamada de <code>Main</code> como o ponto para capturar uma exce√ß√£o, mas a pilha inteira antes do ponto de lan√ßar uma exce√ß√£o mais a segunda entrada no <code>Main</code> por c√≥digo n√£o gerenciado.  Podemos supor que esse c√≥digo seja exatamente o c√≥digo para lan√ßar exce√ß√µes que est√£o no est√°gio de filtrar e escolher um manipulador final.  No entanto, <em>nem todas as chamadas podem ser tratadas sem o desenrolar da pilha</em> .  Acredito que a uniformidade excessiva da plataforma gera muita confian√ßa nela.  Por exemplo, quando um dom√≠nio chama um m√©todo de outro dom√≠nio, √© absolutamente transparente em termos de c√≥digo.  No entanto, a maneira como os m√©todos chamam trabalho √© uma hist√≥ria absolutamente diferente.  N√≥s vamos falar sobre eles na pr√≥xima parte. </p><br><h3 id="serialization">  Serializa√ß√£o </h3><br><p>  Vamos come√ßar analisando os resultados da execu√ß√£o do c√≥digo a seguir (adicionei a transfer√™ncia de uma chamada atrav√©s do limite entre dois dom√≠nios de aplicativo). </p><br><pre> <code class="plaintext hljs"> class Program { static void Main() { try { ProxyRunner.Go(); } catch (Exception ex) when (Check(ex)) { ; } } static bool Check(Exception ex) { var domain = AppDomain.CurrentDomain.FriendlyName; // -&gt; TestApp.exe return ex.Message == "1"; } public class ProxyRunner : MarshalByRefObject { private void MethodInsideAppDomain() { throw new Exception("1"); } public static void Go() { var dom = AppDomain.CreateDomain("PseudoIsolated", null, new AppDomainSetup { ApplicationBase = AppDomain.CurrentDomain.BaseDirectory }); var proxy = (ProxyRunner) dom.CreateInstanceAndUnwrap(typeof(ProxyRunner).Assembly.FullName, typeof(ProxyRunner).FullName); proxy.MethodInsideAppDomain(); } } }</code> </pre><br><p>  Podemos ver que o desenrolar da pilha acontece antes de come√ßarmos a filtrar.  Vamos ver as capturas de tela.  O primeiro √© obtido antes da gera√ß√£o de uma exce√ß√£o: </p><br><p><img src="https://habrastorage.org/getpro/habr/post_images/bda/8d8/792/bda8d87928516a8213cafdf953d029b6.png" alt="Stackunnroll"></p><br><p>  O segundo √© depois: </p><br><p><img src="https://habrastorage.org/getpro/habr/post_images/c2b/f45/dee/c2bf45dee3a13091259468415719dbea.png" alt="Stackacknroll2"></p><br><p>  Vamos estudar o rastreamento de chamadas antes e depois das exce√ß√µes serem filtradas.  O que acontece aqui?  Podemos ver que os desenvolvedores de plataformas criaram algo que, √† primeira vista, parece a prote√ß√£o de um subdom√≠nio.  O rastreamento √© cortado ap√≥s o √∫ltimo m√©todo na cadeia de chamadas e, em seguida, h√° a transfer√™ncia para outro dom√≠nio.  Mas acho isso estranho.  Para entender por que isso acontece, lembre-se da regra principal para tipos que organizam a intera√ß√£o entre dom√≠nios.  Esses tipos devem herdar <code>MarshalByRefObject</code> e ser serializ√°veis.  No entanto, apesar do rigor dos tipos de exce√ß√£o em C #, pode ser de qualquer natureza.  O que isso significa?  Isso significa que situa√ß√µes podem ocorrer quando uma exce√ß√£o dentro de um subdom√≠nio pode ser capturada em um dom√≠nio pai.  Al√©m disso, se um objeto de dados que pode entrar em uma situa√ß√£o excepcional tiver alguns m√©todos perigosos em termos de seguran√ßa, ele poder√° ser chamado em um dom√≠nio pai.  Para evitar isso, a exce√ß√£o √© primeiro serializada e, em seguida, cruza a fronteira entre os dom√≠nios do aplicativo e aparece novamente com uma nova pilha.  Vamos verificar esta teoria: </p><br><pre> <code class="plaintext hljs">[StructLayout(LayoutKind.Explicit)] class Cast { [FieldOffset(0)] public Exception Exception; [FieldOffset(0)] public object obj; } static void Main() { try { ProxyRunner.Go(); Console.ReadKey(); } catch (RuntimeWrappedException ex) when (ex.WrappedException is Program) { ; } } static bool Check(Exception ex) { var domain = AppDomain.CurrentDomain.FriendlyName; // -&gt; TestApp.exe return ex.Message == "1"; } public class ProxyRunner : MarshalByRefObject { private void MethodInsideAppDomain() { var x = new Cast {obj = new Program()}; throw x.Exception; } public static void Go() { var dom = AppDomain.CreateDomain("PseudoIsolated", null, new AppDomainSetup { ApplicationBase = AppDomain.CurrentDomain.BaseDirectory }); var proxy = (ProxyRunner)dom.CreateInstanceAndUnwrap(typeof(ProxyRunner).Assembly.FullName, typeof(ProxyRunner).FullName); proxy.MethodInsideAppDomain(); } }</code> </pre> <br><p>  Como o c√≥digo C # poderia gerar uma exce√ß√£o de qualquer tipo (n√£o quero tortur√°-lo com o MSIL), executei um truque neste exemplo, convertendo um tipo para um n√£o compar√°vel, para que pud√©ssemos lan√ßar uma exce√ß√£o de qualquer tipo, mas o tradutor pensaria que usamos o tipo de <code>Exception</code> .  Criamos uma inst√¢ncia do tipo <code>Program</code> , que n√£o √© serializ√°vel, com certeza, e lan√ßamos uma exce√ß√£o usando esse tipo como carga de trabalho.  A boa not√≠cia √© que voc√™ obt√©m um inv√≥lucro para exce√ß√µes n√£o-Exception de <code>RuntimeWrappedException</code> que armazenar√° uma inst√¢ncia do nosso objeto de tipo de <code>Program</code> dentro e poderemos capturar essa exce√ß√£o.  No entanto, existem m√°s not√≠cias que ap√≥iam nossa ideia: chamar <code>proxy.MethodInsideAppDomain();</code>  ir√° gerar <code>SerializationException</code> : </p><br><p><img src="https://habrastorage.org/getpro/habr/post_images/1ad/ace/7f1/1adace7f1c21e2ad7edc51b36f343dc9.png"></p><br><p>  Portanto, voc√™ n√£o pode transferir uma exce√ß√£o entre dom√≠nios, pois n√£o √© poss√≠vel serializ√°-la.  Isso, por sua vez, significa que o uso de filtros de exce√ß√£o para chamadas de m√©todos de quebra <code>FullTrust</code> em outros dom√≠nios levar√° a desenrolar a pilha, apesar de a serializa√ß√£o parecer desnecess√°ria com <code>FullTrust</code> configura√ß√µes <code>FullTrust</code> de um subdom√≠nio. </p><br><blockquote>  Devemos prestar aten√ß√£o adicional ao motivo pelo qual a serializa√ß√£o entre dom√≠nios √© t√£o necess√°ria.  Em nosso exemplo artificial, criamos um subdom√≠nio que n√£o possui configura√ß√µes.  Isso significa que funciona da maneira FullTrust.  O CLR confia totalmente em seu conte√∫do e n√£o executa verifica√ß√µes adicionais.  No entanto, quando voc√™ insere pelo menos uma configura√ß√£o de seguran√ßa, a confian√ßa total desaparece e o CLR come√ßa a controlar tudo o que acontece dentro de um subdom√≠nio.  Portanto, quando voc√™ tem um dom√≠nio totalmente confi√°vel, n√£o precisa de uma serializa√ß√£o.  Admita, n√£o precisamos nos proteger.  Mas a serializa√ß√£o existe n√£o apenas para prote√ß√£o.  Cada dom√≠nio carrega todos os assemblies necess√°rios uma segunda vez e cria suas c√≥pias.  Assim, ele cria c√≥pias de todos os tipos e todas as VMTs.  Obviamente, ao passar um objeto de dom√≠nio para dom√≠nio, voc√™ obter√° o mesmo objeto.  Mas suas VMTs n√£o ser√£o pr√≥prias e esse objeto n√£o poder√° ser convertido para outro tipo.  Em outras palavras, se criarmos uma inst√¢ncia de um tipo <code>Boo</code> e a colocarmos em outro dom√≠nio, a convers√£o do <code>(Boo)boo</code> n√£o funcionar√°.  Nesse caso, a serializa√ß√£o e a desserializa√ß√£o resolver√£o o problema, pois o objeto existir√° em dois dom√≠nios simultaneamente.  Ele existir√° com todos os seus dados onde foi criado e existir√° no dom√≠nio de uso como um objeto proxy, garantindo que os m√©todos de um objeto original sejam chamados. </blockquote><p>  Ao transferir um objeto serializado entre dom√≠nios, voc√™ obt√©m uma c√≥pia completa do objeto de um dom√≠nio em outro enquanto mant√©m alguma delimita√ß√£o na mem√≥ria.  No entanto, essa delimita√ß√£o √© fict√≠cia.  √â usado apenas para os tipos que n√£o est√£o no <code>Shared AppDomain</code> .  Portanto, se voc√™ lan√ßar algo n√£o serializ√°vel como uma exce√ß√£o, mas no <code>Shared AppDomain</code> , voc√™ n√£o receber√° um erro de serializa√ß√£o (podemos tentar lan√ßar <code>Action</code> vez de <code>Program</code> ).  No entanto, o desenrolar da pilha ocorrer√° de qualquer maneira neste caso: as duas variantes devem funcionar de maneira padr√£o.  Para que ningu√©m fique confuso. </p><br><blockquote><img src="https://habrastorage.org/webt/tu/qf/aq/tuqfaqcncvjtdmb_uxgcbbzyr9o.png" align="left">  Este cap√≠tulo foi traduzido do russo em conjunto pelo autor e por <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=pt&amp;u=">tradutores profissionais</a> .  Voc√™ pode nos ajudar com a tradu√ß√£o do russo ou do ingl√™s para qualquer outro idioma, principalmente para chin√™s ou alem√£o. <br><br>  Al√©m disso, se voc√™ quiser nos agradecer, a melhor maneira de fazer isso √© nos dar uma estrela no github ou no fork do reposit√≥rio <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=pt&amp;u="><img src="https://habrastorage.org/webt/5n/wo/6u/5nwo6uvyk2eafkzdd0cdofjqm-0.png" width="22"></a>  <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=pt&amp;u=">github / sidristij / dotnetbook</a> . <br></blockquote></div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/pt454630/">https://habr.com/ru/post/pt454630/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../pt454618/index.html">Po√ßo da produtividade: como o Slack prejudica nosso fluxo de trabalho</a></li>
<li><a href="../pt454620/index.html">#NoDeployFriday: ajuda ou prejudica?</a></li>
<li><a href="../pt454622/index.html">Kreisel EVEX 910e: modelo hist√≥rico - nova vida</a></li>
<li><a href="../pt454626/index.html">DevOops ontem e hoje</a></li>
<li><a href="../pt454628/index.html">Construindo um Sistema Autom√°tico de Modera√ß√£o de Mensagens</a></li>
<li><a href="../pt454634/index.html">Semana 23 de Seguran√ßa: Vulnerabilidade no bloco de notas, um milh√£o de sistemas com RDP sem patch</a></li>
<li><a href="../pt454640/index.html">Depura√ß√£o remota de microsservi√ßos via SSH sob VPN em 4 turnos</a></li>
<li><a href="../pt454642/index.html">‚ÄúFa√ßa uma inscri√ß√£o para as pessoas‚Äù - isso n√£o deve ser rabiscado no joelho ‚Äù: sobre o desenvolvimento m√≥vel na CFT</a></li>
<li><a href="../pt454644/index.html">Treinamento Cisco 200-125 CCNA v3.0. Dia 8. Alternar configura√ß√£o</a></li>
<li><a href="../pt454646/index.html">@Pythonetc compilation, maio de 2019</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>