<!doctype html>
<html class="no-js" lang="en">

<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-134228602-6"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-134228602-6');
  </script>

  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>üêú ‚òÇÔ∏è üëéüèª Les exceptions Python sont d√©sormais consid√©r√©es comme anti-mod√®le ü§ûüèª ‚õ≤Ô∏è üòõ</title>
  <link rel="icon" type="image/x-icon" href="/favicon.ico" />
  <meta name="description" content="Quelles sont les exceptions? D'apr√®s le nom, c'est clair - ils surviennent lorsqu'une exception se produit dans le programme. Vous pouvez vous demande...">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="../../css/main.css">

  <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="../../js/vendors/jquery-3.3.1.min.js"><\/script>')</script>

  <script>document.write('<script src="//pagea' + 'd2.googles' + 'yndication.com/pagea' + 'd/js/a' + 'dsby' + 'google.js"><\/script>')</script>
  <script>
        var superSpecialObject = {};
        superSpecialObject['google_a' + 'd_client'] = 'ca-p' + 'ub-6974184241884155';
        superSpecialObject['enable_page_level_a' + 'ds'] = true;
       (window['a' + 'dsbygoogle'] = window['a' + 'dsbygoogle'] || []).push(superSpecialObject);
  </script>
</head>

<body>
  <!--[if lte IE 9]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->
  <header class="page-header js-page-header">
    <a class="page-header-logo-container" href="https://weekly-geekly-es.github.io/index.html"></a>
    <div class="page-header-text">Geekly articles weekly</div>
  </header>
  <section class="page js-page"><h1>Les exceptions Python sont d√©sormais consid√©r√©es comme anti-mod√®le</h1><div class="post__body post__body_full"><div class="post__text post__text-html post__text_v1" id="post-content-body" data-io-article-url="https://habr.com/ru/company/oleg-bunin/blog/445234/">  Quelles sont les exceptions?  D'apr√®s le nom, c'est clair - ils surviennent lorsqu'une exception se produit dans le programme.  Vous pouvez vous demander pourquoi les exceptions sont un anti-mod√®le et comment sont-elles li√©es √† la frappe?  J'ai essay√© de <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">comprendre</a> , et maintenant je veux en discuter avec vous, harazhiteli. <br><br><h2>  Probl√®mes d'exception </h2><br>  Il est difficile de trouver des failles dans ce √† quoi vous faites face tous les jours.  L'habitude et la c√©cit√© transforment les bogues en fonctionnalit√©s, mais essayons d'examiner les exceptions avec un esprit ouvert. <br><br><h3>  Les exceptions sont difficiles √† rep√©rer </h3><br>  Il existe deux types d'exceptions: les ¬´explicites¬ª sont cr√©√©es en appelant <code>raise</code> directement dans le code que vous lisez;  ¬´Cach√©¬ª est cach√© dans les fonctions, classes et m√©thodes utilis√©es. <br><br>  Le probl√®me est que les exceptions ¬´cach√©es¬ª sont vraiment difficiles √† remarquer.  Permettez-moi de vous montrer un exemple de fonction pure: <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second</code> </pre><br>  La fonction divise simplement un nombre par un autre, renvoyant un <code>float</code> .  Les types sont v√©rifi√©s et vous pouvez ex√©cuter quelque chose comme ceci: <br><br><pre> <code class="python hljs">result = divide(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>) print(<span class="hljs-string"><span class="hljs-string">'x / y = '</span></span>, result)</code> </pre><br>  L'avez-vous remarqu√©?  En fait, l'ex√©cution du programme n'atteindra jamais l' <code>print</code> , car la division de 1 par 0 est une op√©ration impossible, elle <code>ZeroDivisionError</code> une <code>ZeroDivisionError</code> .  Oui, ce code est s√ªr pour le type, mais il ne peut pas √™tre utilis√© de toute fa√ßon. <br><a name="habracut"></a><br>  Pour remarquer un probl√®me potentiel m√™me dans un code aussi simple et lisible, il faut de l'exp√©rience.  Tout en Python peut cesser de fonctionner avec diff√©rents types d'exceptions: division, appels de fonction, <code>int</code> , <code>str</code> , g√©n√©rateurs, it√©rateurs en boucles, acc√®s aux attributs ou aux cl√©s.  M√™me <code>raise something()</code> peut provoquer un crash.  De plus, je ne mentionne m√™me pas les op√©rations d'entr√©e et de sortie.  Et <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">les exceptions v√©rifi√©es ne seront plus prises</a> en <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">charge</a> dans un avenir proche. <br><br><h3>  Il n'est pas possible de r√©tablir un comportement normal en place </h3><br>  Mais pr√©cis√©ment pour un tel cas, nous avons des exceptions.  Prenons simplement <code>ZeroDivisionError</code> et le code deviendra s√ªr pour le type. <br><br><pre> <code class="python hljs"><span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second <span class="hljs-keyword"><span class="hljs-keyword">except</span></span> ZeroDivisionError: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> <span class="hljs-number"><span class="hljs-number">0.0</span></span></code> </pre><br>  Maintenant tout va bien.  Mais pourquoi renvoyons-nous 0?  Pourquoi pas 1 ou <code>None</code> ?  Bien s√ªr, dans la plupart des cas, obtenir <code>None</code> presque aussi mauvais (sinon pire) qu'une exception, mais vous devez toujours vous fier √† la logique m√©tier et aux options pour utiliser la fonction. <br><br>  Que partageons-nous exactement?  Des nombres arbitraires, des unit√©s sp√©cifiques ou de l'argent?  Toutes les options ne sont pas faciles √† pr√©voir et √† restaurer.  Il peut s'av√©rer que la prochaine fois que vous utilisez une fonction, il s'av√®re que vous avez besoin d'une logique de r√©cup√©ration diff√©rente. <br><br><blockquote>  La triste conclusion: la solution √† chaque probl√®me est individuelle, selon le contexte sp√©cifique d'utilisation. </blockquote><br>  Il n'y a pas de <code>ZeroDivisionError</code> miracle pour faire face √† <code>ZeroDivisionError</code> une fois pour toutes.  Et nous ne parlons pas de la possibilit√© d'E / S complexes avec des demandes et des d√©lais d'expiration r√©p√©t√©s. <br><br>  Peut-√™tre qu'il n'est pas n√©cessaire de g√©rer les exceptions exactement o√π elles se produisent?  Peut-√™tre simplement le jeter dans le processus d'ex√©cution du code - quelqu'un le d√©couvrira plus tard.  Et puis nous sommes oblig√©s de revenir √† l'√©tat actuel des choses. <br><br><h3>  Le processus d'ex√©cution n'est pas clair </h3><br>  Eh bien, esp√©rons que quelqu'un d'autre intercepte l'exception et peut-√™tre la g√®re.  Par exemple, le syst√®me peut demander √† l'utilisateur de modifier la valeur entr√©e, car elle ne peut pas √™tre divis√©e par 0. Et la fonction de <code>divide</code> ne doit pas √™tre explicitement responsable de la r√©cup√©ration apr√®s l'erreur. <br><br>  Dans ce cas, vous devez v√©rifier o√π nous avons intercept√© l'exception.  Soit dit en passant, comment d√©terminer exactement o√π il sera trait√©?  Est-il possible d'aller au bon endroit dans le code?  Il s‚Äôav√®re que non, <strong>c‚Äôest impossible</strong> . <br><br>  Il n'est pas possible de d√©terminer la ligne de code qui s'ex√©cutera apr√®s la lev√©e de l'exception.  Diff√©rents types d'exceptions peuvent √™tre g√©r√©s avec diff√©rentes options <code>except</code> , et certaines exceptions peuvent √™tre <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">ignor√©es</a> .  Et vous pouvez lever des exceptions suppl√©mentaires dans d'autres modules qui seront ex√©cut√©s plus t√¥t, et en g√©n√©ral rompre toute la logique. <br><br>  Supposons qu'il existe deux threads ind√©pendants dans une application: un thread normal qui s'ex√©cute de haut en bas et un thread d'exception qui s'ex√©cute √† sa guise.  Comment lire et comprendre ce code? <br><br>  Uniquement avec le d√©bogueur activ√© en mode "intercepter toutes les exceptions". <br><br><div style="text-align:center;"><img src="https://habrastorage.org/webt/8k/bn/do/8kbndolwukkaluarfk3vpexws2w.png"></div><br>  Des exceptions, comme le <code>goto</code> notoire, d√©chirent la structure du programme. <br><br><h3>  Les exceptions ne sont pas exclusives </h3><br>  Regardons un autre exemple: le code d'acc√®s API HTTP distant habituel: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> requests <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">fetch_user_profile</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(user_id: int)</span></span></span><span class="hljs-function"> -&gt; 'UserProfile':</span></span> <span class="hljs-string"><span class="hljs-string">"""Fetches UserProfile dict from foreign API."""</span></span> response = requests.get(<span class="hljs-string"><span class="hljs-string">'/api/users/{0}'</span></span>.format(user_id)) response.raise_for_status() <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> response.json()</code> </pre><br>  Dans cet exemple, tout peut litt√©ralement mal se passer.  Voici une liste partielle des erreurs possibles: <br><br><ul><li>  Le r√©seau peut ne pas √™tre disponible et la demande ne sera pas ex√©cut√©e du tout. </li><li>  Le serveur peut ne pas fonctionner. </li><li>  Le serveur est peut-√™tre trop occup√©, un d√©lai d'attente se produit. </li><li>  Le serveur peut n√©cessiter une authentification. </li><li>  Une API peut ne pas avoir une telle URL. </li><li>  Un utilisateur inexistant peut √™tre transf√©r√©. </li><li>  Peut-√™tre pas assez de droits. </li><li>  Le serveur peut se bloquer en raison d'une erreur interne lors du traitement de votre demande </li><li>  Le serveur peut renvoyer une r√©ponse invalide ou endommag√©e. </li><li>  Le serveur peut renvoyer un JSON non valide qui ne peut pas √™tre analys√©. </li></ul><br>  La liste s'allonge encore et encore, tant de probl√®mes potentiels r√©sident dans le code des trois malheureuses lignes.  Nous pouvons dire que cela ne fonctionne g√©n√©ralement que par une chance, et est beaucoup plus susceptible de tomber avec une exception. <br><br><h2>  Comment se prot√©ger? </h2><br>  Maintenant que nous nous sommes assur√©s que les exceptions peuvent nuire au code, essayons de les √©liminer.  Pour √©crire du code sans exception, il existe diff√©rents mod√®les. <br><br><ul><li>  Partout √©crire <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">except Exception: pass</a></code> .  Impasse.  <strong>Ne le faites pas.</strong> </li><li>  Retour <code>None</code> .  Trop mal.  En cons√©quence, vous devrez soit commencer presque toutes les lignes avec <code>if something is not None:</code> et toute la logique sera perdue derri√®re les ordures des contr√¥les de nettoyage, soit souffrir de <code>TypeError</code> tout le temps.  Pas un bon choix. </li><li>  √âcrivez des classes pour des cas d'utilisation sp√©ciaux.  Par exemple, la classe de base <code>User</code> avec des sous-classes pour les erreurs comme <code>UserNotFound</code> et <code>MissingUser</code> .  Cette approche peut √™tre utilis√©e dans certaines situations sp√©cifiques, telles que <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">AnonymousUser</a></code> dans Django, mais envelopper toutes les erreurs possibles dans les classes est irr√©aliste.  Cela demandera trop de travail et le mod√®le de domaine deviendra incroyablement complexe. </li><li>  Utilisez des conteneurs pour encapsuler la variable ou la valeur d'erreur r√©sultante dans un wrapper et continuez √† travailler avec la valeur du conteneur.  C'est pourquoi nous avons cr√©√© le projet <code><a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">@dry-python/return</a></code> .  Ainsi, les fonctions renvoient quelque chose de significatif, de typ√© et de s√ªr. </li></ul><br>  Revenons √† l'exemple de division, qui renvoie 0 en cas d'erreur. Peut-on indiquer explicitement que la fonction n'a pas r√©ussi sans retourner une valeur num√©rique sp√©cifique? <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; Result[float, ZeroDivisionError]:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Success(first / second) <span class="hljs-keyword"><span class="hljs-keyword">except</span></span> ZeroDivisionError <span class="hljs-keyword"><span class="hljs-keyword">as</span></span> exc: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Failure(exc)</code> </pre><br>  Nous enfermons les valeurs dans l'un des deux wrappers: <code>Success</code> ou <code>Failure</code> .  Ces classes sont h√©rit√©es de la classe de base <code>Result</code> .  Les types de valeurs compress√©es peuvent √™tre sp√©cifi√©s dans l'annotation avec la fonction renvoy√©e, par exemple, <code>Result[float, ZeroDivisionError]</code> renvoie <code>Success[float]</code> ou <code>Failure[ZeroDivisionError]</code> . <br><br>  Qu'est-ce que cela nous donne?  Plus d' <strong>exceptions ne sont pas exceptionnelles, mais sont des probl√®mes attendus</strong> .  En outre, l'encapsulation d'une exception dans <code>Failure</code> r√©sout un deuxi√®me probl√®me: la complexit√© de l'identification des exceptions potentielles. <br><br><pre> <code class="python hljs"><span class="hljs-number"><span class="hljs-number">1</span></span> + divide(<span class="hljs-number"><span class="hljs-number">1</span></span>, <span class="hljs-number"><span class="hljs-number">0</span></span>) <span class="hljs-comment"><span class="hljs-comment"># =&gt; mypy error: Unsupported operand types for + ("int" and "Result[float, ZeroDivisionError]")</span></span></code> </pre><br>  Maintenant, ils sont faciles √† rep√©rer.  Si vous voyez <code>Result</code> dans le code, la fonction peut lever une exception.  Et vous connaissez m√™me son type √† l'avance. <br><br>  De plus, la biblioth√®que est enti√®rement typ√©e et <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">compatible avec PEP561</a> .  Autrement dit, mypy vous avertira si vous essayez de renvoyer quelque chose qui ne correspond pas au type d√©clar√©. <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; Result[float, ZeroDivisionError]:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">try</span></span>: <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> Success(<span class="hljs-string"><span class="hljs-string">'Done'</span></span>) <span class="hljs-comment"><span class="hljs-comment"># =&gt; error: incompatible type "str"; expected "float" except ZeroDivisionError as exc: return Failure(0) # =&gt; error: incompatible type "int"; expected "ZeroDivisionError"</span></span></code> </pre><br><h3>  Comment travailler avec des conteneurs? </h3><br>  Il existe deux <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">m√©thodes</a> : <br><br><ul><li>  <code>map</code> fonctions qui renvoient des valeurs normales; </li><li>  <code>bind</code> pour les fonctions qui renvoient d'autres conteneurs. </li></ul><br><pre> <code class="python hljs">Success(<span class="hljs-number"><span class="hljs-number">4</span></span>).bind(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number / <span class="hljs-number"><span class="hljs-number">2</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Success(2) Success(4).map(lambda number: number + 1) # =&gt; Success(5)</span></span></code> </pre><br>  La beaut√© est que ce code vous prot√©gera des scripts infructueux, car <code>.bind</code> et <code>.map</code> ne s'ex√©cuteront pas pour les conteneurs avec <code>Failure</code> : <br><br><pre> <code class="python hljs">Failure(<span class="hljs-number"><span class="hljs-number">4</span></span>).bind(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number / <span class="hljs-number"><span class="hljs-number">2</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Failure(4) Failure(4).map(lambda number: number / 2) # =&gt; Failure(4)</span></span></code> </pre><br>  Maintenant, vous pouvez simplement vous concentrer sur le processus d'ex√©cution correct et √™tre s√ªr qu'un mauvais √©tat ne cassera pas le programme dans un endroit inattendu.  Et il y a toujours la possibilit√© de <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">d√©terminer le mauvais √©tat, de le corriger</a> et de revenir sur le chemin con√ßu du processus. <br><br><pre> <code class="python hljs">Failure(<span class="hljs-number"><span class="hljs-number">4</span></span>).rescue(<span class="hljs-keyword"><span class="hljs-keyword">lambda</span></span> number: Success(number + <span class="hljs-number"><span class="hljs-number">1</span></span>)) <span class="hljs-comment"><span class="hljs-comment"># =&gt; Success(5) Failure(4).fix(lambda number: number / 2) # =&gt; Success(2)</span></span></code> </pre><br>  Dans notre approche, ¬´tous les probl√®mes sont r√©solus individuellement¬ª et ¬´le processus d'ex√©cution est d√©sormais transparent¬ª.  Profitez d'une programmation qui roule sur des rails! <br><br><h3>  Mais comment augmenter les valeurs des conteneurs? </h3><br>  En effet, si vous travaillez avec des fonctions qui ne connaissent rien aux conteneurs, vous avez besoin des valeurs elles-m√™mes.  Ensuite, vous pouvez utiliser les <code>.unwrap()</code> ou <code>.value_or()</code> : <br><br><pre> <code class="python hljs">Success(<span class="hljs-number"><span class="hljs-number">1</span></span>).unwrap() <span class="hljs-comment"><span class="hljs-comment"># =&gt; 1 Success(0).value_or(None) # =&gt; 0 Failure(0).value_or(None) # =&gt; None Failure(1).unwrap() # =&gt; Raises UnwrapFailedError()</span></span></code> </pre><br>  Attendez, nous avons d√ª nous d√©barrasser des exceptions, et maintenant il s'av√®re que tous les <code>.unwrap()</code> peuvent conduire √† une autre exception? <br><br><h3>  Comment ne pas penser √† UnwrapFailedErrors? </h3><br>  Ok, voyons comment vivre avec les nouvelles exceptions.  Consid√©rez cet exemple: vous devez v√©rifier les entr√©es utilisateur et cr√©er deux mod√®les dans la base de donn√©es.  Chaque √©tape peut se terminer par une exception, c'est pourquoi toutes les m√©thodes sont encapsul√©es dans <code>Result</code> : <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result, Success, Failure <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> <span class="hljs-comment"><span class="hljs-comment"># </span><span class="hljs-doctag"><span class="hljs-comment"><span class="hljs-doctag">TODO:</span></span></span><span class="hljs-comment"> we need to create a pipeline of these methods somehow... def _validate_user( self, username: str, email: str, ) -&gt; Result['UserSchema', str]: """Returns an UserSchema for valid input, otherwise a Failure.""" def _create_account( self, user_schema: 'UserSchema', ) -&gt; Result['Account', str]: """Creates an Account for valid UserSchema's. Or returns a Failure.""" def _create_user( self, account: 'Account', ) -&gt; Result['User', str]: """Create an User instance. If user already exists returns Failure."""</span></span></code> </pre><br>  Premi√®rement, vous n'avez pas du tout √† √©tendre les valeurs dans votre propre logique m√©tier: <br><br><pre> <code class="python hljs"><span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">__call__</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, username: str, email: str)</span></span></span><span class="hljs-function"> -&gt; Result['User', str]:</span></span> <span class="hljs-string"><span class="hljs-string">"""Can return a Success(user) or Failure(str_reason)."""</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> self._validate_user( username, email, ).bind( self._create_account, ).bind( self._create_user, ) <span class="hljs-comment"><span class="hljs-comment"># ...</span></span></code> </pre><br>  Tout fonctionnera sans aucun probl√®me, aucune exception ne sera <code>.unwrap()</code> , car <code>.unwrap()</code> pas utilis√©.  Mais est-il facile de lire un tel code?  Non.  Et quelle est l'alternative?  <code>@pipeline</code> : <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> result.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> pipeline <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">CreateAccountAndUser</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Creates new Account-User pair."""</span></span> @pipeline <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">__call__</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(self, username: str, email: str)</span></span></span><span class="hljs-function"> -&gt; Result['User', str]:</span></span> <span class="hljs-string"><span class="hljs-string">"""Can return a Success(user) or Failure(str_reason)."""</span></span> user_schema = self._validate_user(username, email).unwrap() account = self._create_account(user_schema).unwrap() <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> self._create_user(account) <span class="hljs-comment"><span class="hljs-comment"># ...</span></span></code> </pre><br>  Maintenant, ce code est bien lu.  Voici comment <code>.unwrap()</code> et <code>@pipeline</code> fonctionnent ensemble: chaque fois qu'une m√©thode <code>.unwrap()</code> √©choue et √©choue <code>Failure[str]</code> , le d√©corateur <code>@pipeline</code> attrape et renvoie <code>Failure[str]</code> comme valeur r√©sultante.  C'est ainsi que je propose de supprimer toutes les exceptions du code et de le rendre vraiment s√ªr et typ√©. <br><br><h2>  Envelopper le tout ensemble </h2><br>  Eh bien, nous allons maintenant appliquer les nouveaux outils, par exemple, avec une demande √† l'API HTTP.  N'oubliez pas que chaque ligne peut lever une exception?  Et il n'y a aucun moyen de leur faire retourner le conteneur avec <code>Result</code> .  Mais vous pouvez utiliser le <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">d√©corateur @safe</a> pour <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">encapsuler les</a> fonctions dangereuses et les s√©curiser.  Voici deux options de code qui font la m√™me chose: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> safe @safe <span class="hljs-function"><span class="hljs-keyword"><span class="hljs-function"><span class="hljs-keyword">def</span></span></span><span class="hljs-function"> </span><span class="hljs-title"><span class="hljs-function"><span class="hljs-title">divide</span></span></span><span class="hljs-params"><span class="hljs-function"><span class="hljs-params">(first: float, second: float)</span></span></span><span class="hljs-function"> -&gt; float:</span></span> <span class="hljs-keyword"><span class="hljs-keyword">return</span></span> first / second <span class="hljs-comment"><span class="hljs-comment"># is the same as: def divide(first: float, second: float) -&gt; Result[float, ZeroDivisionError]: try: return Success(first / second) except ZeroDivisionError as exc: return Failure(exc)</span></span></code> </pre><br>  La premi√®re, avec <code>@safe</code> , est plus facile et meilleure √† lire. <br><br>  La derni√®re chose √† faire dans l'exemple de demande d'API est d'ajouter le d√©corateur <code>@safe</code> .  Le r√©sultat est le code suivant: <br><br><pre> <code class="python hljs"><span class="hljs-keyword"><span class="hljs-keyword">import</span></span> requests <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.functions <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> pipeline, safe <span class="hljs-keyword"><span class="hljs-keyword">from</span></span> returns.result <span class="hljs-keyword"><span class="hljs-keyword">import</span></span> Result <span class="hljs-class"><span class="hljs-keyword"><span class="hljs-class"><span class="hljs-keyword">class</span></span></span><span class="hljs-class"> </span><span class="hljs-title"><span class="hljs-class"><span class="hljs-title">FetchUserProfile</span></span></span><span class="hljs-params"><span class="hljs-class"><span class="hljs-params">(object)</span></span></span><span class="hljs-class">:</span></span> <span class="hljs-string"><span class="hljs-string">"""Single responsibility callable object that fetches user profile."""</span></span> <span class="hljs-comment"><span class="hljs-comment">#: You can later use dependency injection to replace `requests` #: with any other http library (or even a custom service). _http = requests @pipeline def __call__(self, user_id: int) -&gt; Result['UserProfile', Exception]: """Fetches UserProfile dict from foreign API.""" response = self._make_request(user_id).unwrap() return self._parse_json(response) @safe def _make_request(self, user_id: int) -&gt; requests.Response: response = self._http.get('/api/users/{0}'.format(user_id)) response.raise_for_status() return response @safe def _parse_json(self, response: requests.Response) -&gt; 'UserProfile': return response.json()</span></span></code> </pre><br>  <strong>Pour r√©sumer comment supprimer les exceptions et s√©curiser le code</strong> : <br><br><ul><li>  Utilisez le wrapper <code>@safe</code> pour toutes les m√©thodes susceptibles de <code>@safe</code> une exception.  Il changera le type de retour de la fonction en <code>Result[OldReturnType, Exception]</code> . </li><li>  Utilisez <code>Result</code> comme conteneur pour transf√©rer les valeurs et les erreurs dans une abstraction simple. </li><li>  Utilisez <code>.unwrap()</code> pour d√©velopper la valeur du conteneur. </li><li>  Utilisez <code>@pipeline</code> pour faciliter la <code>.unwrap</code> des <code>.unwrap</code> appels <code>.unwrap</code> . </li></ul><br>  En observant ces r√®gles, nous pouvons faire exactement la m√™me chose - seulement s√ªr et bien lisible.  Tous les probl√®mes li√©s aux exceptions ont √©t√© r√©solus: <br><br><ul><li>  <strong>"Les exceptions sont difficiles √† rep√©rer</strong> . <strong>"</strong>  Maintenant, ils sont envelopp√©s dans un conteneur de <code>Result</code> typ√©, ce qui les rend compl√®tement transparents. </li><li>  <strong>"Il est impossible de r√©tablir un comportement normal en place</strong> . <strong>"</strong>  Vous pouvez maintenant d√©l√©guer en toute s√©curit√© le processus de r√©cup√©ration √† l'appelant.  Dans un tel cas, il existe <code>.fix()</code> et <code>.rescue()</code> . </li><li>  <strong>"La s√©quence d'ex√©cution n'est pas claire</strong> . <strong>"</strong>  Maintenant, ils ne font qu'un avec le flux commercial habituel.  Du d√©but √† la fin. </li><li>  <strong>"Les exceptions ne sont pas exceptionnelles</strong> . <strong>"</strong>  Nous le savons!  Et nous nous attendons √† ce que quelque chose se passe mal et soit pr√™t √† tout. </li></ul><br><h3>  Cas d'utilisation et limitations </h3><br>  De toute √©vidence, vous ne pouvez pas utiliser cette approche dans tout votre code.  Il sera <strong>trop s√ªr</strong> pour la plupart des situations quotidiennes et est incompatible avec d'autres biblioth√®ques ou frameworks.  Mais vous devez √©crire les parties les plus importantes de votre logique m√©tier exactement comme je l'ai montr√©, afin d'assurer le bon fonctionnement de votre syst√®me et de faciliter le support futur. <br><br><blockquote>  Le sujet vous fait-il penser ou semble-t-il holivarny?  Venez √† <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">Moscou Python Conf ++</a> le 5 avril, nous discuterons!  Outre moi, Artyom Malyshev, fondateur du projet dry-python et d√©veloppeur principal de Django Channels, sera l√†.  Il <a href="https://translate.googleusercontent.com/translate_c?depth=1&amp;pto=nl&amp;rurl=translate.google.com&amp;sl=ru&amp;sp=nmt4&amp;tl=fr&amp;u=">parlera</a> davantage de dry-python et de logique m√©tier. </blockquote></div></div><p>Source: <a rel="nofollow" href="https://habr.com/ru/post/fr445234/">https://habr.com/ru/post/fr445234/</a></p>
<section class="more-articles-navigation-panel js-more-articles-navigation-panel">
<h4>More articles:</h4>
<nav class="list-of-articles-container js-list-of-articles-container"><ul class="list-of-pages js-list-of-pages">
<li><a href="../fr445220/index.html">AMD Radeon VII: puce haut de gamme (partie 3)</a></li>
<li><a href="../fr445222/index.html">Recevez une offre en 1 jour √† l'√©quipe back-end lors de la Cosmonautics Day</a></li>
<li><a href="../fr445226/index.html">Le d√©veloppement d'une fus√©e capable d'atteindre la lune co√ªtera √† la Russie 740 milliards de roubles</a></li>
<li><a href="../fr445228/index.html">Cryptographie en Java. Classe Mac</a></li>
<li><a href="../fr445230/index.html">D√©but des inscriptions √† la II conf√©rence informatique pour d√©butants SMARTRHINO-2019</a></li>
<li><a href="../fr445236/index.html">¬´Extreme NOW Forum 2019¬ª: ouverture des inscriptions</a></li>
<li><a href="../fr445238/index.html">Grandir: les 10 meilleurs rapports de Mobius 2018 Moscou</a></li>
<li><a href="../fr445240/index.html">Comment d√©placer, t√©l√©charger et int√©grer de tr√®s grandes donn√©es √† moindre co√ªt et rapidement? Qu'est-ce que l'optimisation pushdown?</a></li>
<li><a href="../fr445242/index.html">Exp√©rience avec Coroutines et Retrofit2</a></li>
<li><a href="../fr445244/index.html">¬´Les jeux d'argent en dehors de la blockchain doivent mourir¬ª</a></li>
</ul></nav>
</section><br />
<a href="../../allArticles.html"><strong>All Articles</strong></a>
<script src="../../js/main.js"></script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter57283870 = new Ya.Metrika({
                  id:57283870,
                  clickmap:true,
                  trackLinks:true,
                  accurateTrackBounce:true,
                  webvisor:true
              });
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = "https://mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/57283870" style="position:absolute; left:-9999px;" alt="" /></div></noscript>

<!-- Google Analytics -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-134228602-6', 'auto'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>

</section>

<footer class="page-footer">
  <div class="page-footer-legal-info-container page-footer-element">
    <p>
      Weekly-Geekly ES | <span class="page-footer-legal-info-year js-page-footer-legal-info-year">2019</span>
    </p>
  </div>
  <div class="page-footer-counters-container page-footer-element">
    <a class="page-footer-counter-clustrmap" href='#'  title='Visit tracker'><img src='https://clustrmaps.com/map_v2.png?cl=698e5a&w=271&t=t&d=9uU9J9pq8z7k8xEBHYSfs6DenIBAHs3vLIHcPIJW9d0&co=3a3a3a&ct=ffffff'/></a>
  </div>
</footer>
  
</body>

</html>